/* Rain Station Z — Survival Handbook
   Page content + page-turn navigation. Item data comes from js/data.js
   (generated by tools/build_data.py — qualitative tiers only, no raw stats).
   Japanese edition pages live in js/manual_ja.js (loaded before this file);
   ?lang=ja switches to them. Item names stay in English in both editions,
   matching the game. */

(function () {
  "use strict";

  /* Language pick, in priority order:
     1. explicit ?lang= in the URL (the toggle) — also remembered for next visit
     2. the choice remembered from a previous visit
     3. the browser's preferred languages (Japanese browsers open the JA book)  */
  const urlLang = new URLSearchParams(location.search).get("lang");
  let lang = (urlLang === "ja" || urlLang === "en") ? urlLang : null;
  if (lang) {
    try { localStorage.setItem("rsz-lang", lang); } catch (e) { /* private mode */ }
  } else {
    try { lang = localStorage.getItem("rsz-lang"); } catch (e) { /* private mode */ }
  }
  if (lang !== "ja" && lang !== "en") {
    const prefs = navigator.languages || [navigator.language || ""];
    lang = prefs.some(l => (l || "").toLowerCase().startsWith("ja")) ? "ja" : "en";
  }
  const LANG = lang === "ja" ? "ja" : "en";

  /* ------------------------------------------------ stat vocabulary ---- */

  const TIER3 = ["Low", "Moderate", "High"];
  const TIER5 = ["Very Low", "Low", "Moderate", "High", "Very High"];

  /* Japanese stat vocabulary. Where the game's own localisation
     (reference/Game.archive) has a term (リロード, ズーム, スタミナ…) we use it. */
  const TIER_JA = {
    "Very Low": "最低", "Low": "低", "Moderate": "中", "High": "高", "Very High": "最高",
  };
  const LABEL_JA = {
    "Damage": "攻撃力", "Durability": "耐久度", "Range": "射程",
    "Accuracy": "命中精度", "Clip Size": "装弾数", "Fire Rate": "連射速度",
    "Reload": "リロード", "Zoom": "ズーム", "Rain Resistance": "防水性",
    "Armour": "防御", "Stamina Bonus": "スタミナ", "Capacity": "容量",
    "Longevity": "寿命", "Vs Survivors": "対生存者", "Vs Undead": "対アンデッド",
  };
  /* Item names and effects come per-language from data.js: name_ja is the
     game's OFFICIAL Japanese (Game.archive loc export), effect_ja is generated
     alongside the English blurb by build_data.py. */
  const CAT_TAG = LANG === "ja" ? {
    handgun: "ハンドガン", rifle: "ライフル", shotgun: "ショットガン",
    crossbow: "クロスボウ", umbrella: "近接・雨よけ",
  } : {
    handgun: "Handgun", rifle: "Rifle", shotgun: "Shotgun",
    crossbow: "Crossbow", umbrella: "Melee &middot; Rain Cover",
  };
  const ABBR = LANG === "ja" ? {
    "Durability": "耐久", "Rain Resistance": "防水", "Armour": "防御",
    "Stamina Bonus": "スタミナ", "Capacity": "容量", "Longevity": "寿命",
  } : {
    "Durability": "Wear", "Rain Resistance": "Rain", "Armour": "Armr",
    "Stamina Bonus": "Stam", "Capacity": "Cap", "Longevity": "Life",
  };

  function trLabel(l) { return LANG === "ja" ? (LABEL_JA[l] || l) : l; }
  function trTier(t) { return LANG === "ja" ? (TIER_JA[t] || t) : t; }
  function itName(it) { return LANG === "ja" ? (it.name_ja || it.name) : it.name; }
  function itEffect(it) { return LANG === "ja" ? (it.effect_ja || it.effect) : it.effect; }

  /* ---------------------------------------------------------- helpers -- */

  function meter(tier) {
    const five = TIER5.indexOf(tier);
    const three = TIER3.indexOf(tier);
    // Moderate/Low/High exist in both scales; prefer the 3-scale when ambiguous
    let idx, total;
    if (three >= 0) { idx = three + 1; total = 3; }
    else { idx = five + 1; total = 5; }
    let s = "";
    for (let i = 0; i < total; i++) s += i < idx ? "&#9632;" : '<span class="off">&#9633;</span>';
    return '<span class="meter">' + s + "</span>";
  }

  function ic(bp) { return "assets/icons/" + RSZ_ITEMS[bp].icon; }

  /* full spec block — weapons */
  function spec(bp) {
    const it = RSZ_ITEMS[bp];
    const rows = it.stats.map(([lbl, tier]) =>
      `<div class="statline"><span class="lbl">${trLabel(lbl)}</span><span class="dots"></span>` +
      `<span class="val">${trTier(tier)} ${meter(tier)}</span></div>`).join("");
    return `<div class="spec">
      <div class="iconbox"><img src="${ic(bp)}" alt="${itName(it)}"></div>
      <div class="info">
        <div class="name"><span>${itName(it)}</span><span class="cat">${CAT_TAG[it.cat] || ""}</span></div>
        <div class="speccols">${rows}</div>
      </div></div>`;
  }

  /* compact grid entry — clothing, consumables */
  function gitem(bp) {
    const it = RSZ_ITEMS[bp];
    let stat;
    if (it.effect) {
      stat = itEffect(it);
    } else {
      stat = it.stats.map(([lbl, tier]) =>
        `${ABBR[lbl] || trLabel(lbl)}&nbsp;${meter(tier)}`).join(" &nbsp;");
    }
    return `<div class="gitem">
      <div class="iconbox"><img src="${ic(bp)}" alt="${itName(it)}"></div>
      <div><div class="gname">${itName(it)}</div><div class="gstat">${stat}</div></div></div>`;
  }

  function jitem(bp) {
    const it = RSZ_ITEMS[bp];
    const lifeWord = LANG === "ja" ? "寿命" : "Life";
    const life = it.stats.length ? `<div class="gstat">${lifeWord} ${meter(it.stats[0][1])}</div>` : "";
    return `<div class="jitem">
      <div class="iconbox"><img src="${ic(bp)}" alt="${itName(it)}"></div>
      <div class="jname">${itName(it)}${life}</div>
      <div class="jeffect">${itEffect(it)}</div></div>`;
  }

  function photo(src, caption, tilt) {
    return `<div class="photoframe ${tilt || ""}">
      <span class="corner tl"></span><span class="corner tr"></span>
      <span class="corner bl"></span><span class="corner br"></span>
      <span class="photo"><img src="assets/${src}" alt="${caption.replace(/<[^>]*>/g, "")}" loading="lazy"></span>
      <div class="caption">${caption}</div></div>`;
  }

  function head(no, title, sub) {
    return `<h1 class="section"><span class="no">${no}</span>${title}` +
      (sub ? `<span class="sub">${sub}</span>` : "") + "</h1>";
  }

  function gaz(list) {
    return '<div class="gazetteer">' +
      list.map(([n, d]) => `<div><b>${n}</b> &mdash; ${d}</div>`).join("") + "</div>";
  }

  const RUN = LANG === "ja"
    ? '<div class="runninghead">レインステーションZ ― サバイバルハンドブック</div>'
    : '<div class="runninghead">Rain Station Z &mdash; Survival Handbook</div>';

  /* ---------------------------------------------------- english pages -- */
  /* Each page: { no: printed page number|null, cls: extra classes, html }
     The Japanese pages mirror these in js/manual_ja.js — keep them in sync. */

  function buildPagesEN() {
    const P = [];

    /* COVER ---------------------------------------------------------------- */
    P.push({ no: null, cls: "cover", html: `
      <img class="logo" src="assets/art/game_logo.png" alt="Rain Station Z">
      <div class="strip">Survival Handbook</div>
      <div class="art">${photo("shots/shot_survivor_portrait.jpg", "Standard-issue optimism not included.")}</div>
      <div class="badges">
        <span class="badge">Steam</span>
        <span class="badge">PlayStation 5</span>
        <span class="badge rating"><span class="big">D</span><span>rated drenched</span></span>
        <span class="badge">Nintendo Switch</span>
      </div>` });

    /* inside front cover — WARNING ----------------------------------------- */
    P.push({ no: null, cls: "stained", html: `
      <div class="warnbox">
        <h3>&#9888; Important Safety Information &#9888;</h3>
        <p class="body"><span class="lead">Warning &mdash; read before going outside.</span>
        Prolonged exposure to RAIN STATION Z may cause elevated heart rate, damp
        socks, a compulsive need to hoard tinned goods, and strong opinions about
        umbrellas. A very small percentage of players may experience the
        sensation of being followed. They are correct.</p>
        <p class="body"><span class="lead">Precipitation notice.</span> The rain in this
        product is not drinking water. Do not lick the rain. If your pH meter
        reads zero, you have already licked the rain. Find shelter immediately.</p>
        <p class="body"><span class="lead">Battery advisory.</span> Torches consume
        batteries. Maps consume batteries. Courage consumes batteries fastest of
        all. Change batteries only in a dry place.</p>
        <p class="body"><span class="lead">To avoid injury:</span> take a 15-minute break
        every hour, even if the horde is at the door. The horde will wait. The
        horde has nothing but time.</p>
      </div>
      <p class="body typewriter" style="text-align:center">This handbook was printed on
      recycled paper. Inside the zone, all paper is recycled paper.</p>
      ${RUN}` });

    /* p1 — title page ------------------------------------------------------- */
    P.push({ no: 1, cls: "stained", html: `
      <div style="text-align:center; margin-top:8%">
        <img src="assets/art/game_logo.png" alt="Rain Station Z" style="width:80%">
        <p class="typewriter" style="margin-top:6%; letter-spacing:.3em; font-size:14px">
          OFFICIAL SURVIVAL HANDBOOK</p>
        <p class="typewriter" style="margin-top:1%; font-size:11px; color:var(--ink-soft)">
          First edition &mdash; slightly water-damaged</p>
        <div style="margin:9% auto; width:55%; border-top:1.5px solid var(--ink); border-bottom:1.5px solid var(--ink); padding:.8em 0">
          <p class="body" style="text-align:center; margin:0">
            It has been raining for a long time.<br>
            This book will help you stay alive.<br>
            Please keep it dry.</p>
        </div>
        <p class="typewriter" style="font-size:11px; color:var(--ink-soft)">
          WOBBLY TOOTH LIMITED</p>
      </div>
      <div class="fieldnote">Found this in a letterbox on my third day. Whoever
      wrote it knew their stuff. I've added my own notes in the margins
      &mdash; ignore them at your peril. Keep dry, don't die. <b>&mdash; M.</b></div>
      ${RUN}` });

    /* p2 — TOC -------------------------------------------------------------- */
    const TOC = [
      ["The Story So Far", 3], ["Know Your Survivor", 4], ["Survivor Actions", 5],
      ["The Rain", 6], ["The Armoury", 8], ["Outfitting", 14],
      ["Provisions &amp; First Aid", 18], ["Survivor's Journals", 20],
      ["Missions", 22], ["The Zone", 24], ["The Undead", 26],
      ["Surviving Together", 27], ["Photo Mode", 28], ["Field Capabilities", 29],
      ["Field Notes", 30], ["Credits", 31],
    ];
    P.push({ no: 2, html: `
      ${head("&#167;", "Contents")}
      <div class="toc">${TOC.map(([t, pg]) =>
        `<div class="tocline" data-goto="${pg}"><span class="t">${t}</span><span class="dots"></span><span class="pg">${pg}</span></div>`).join("")}
      </div>
      <div class="fieldnote">Pages 6 and 7 are the ones that keep you alive.
      Read them twice. <b>&mdash; M.</b></div>
      ${RUN}` });

    /* p3 — story ------------------------------------------------------------ */
    P.push({ no: 3, cls: "stained", html: `
      ${head("1", "The Story So Far")}
      <p class="body">First the weather changed. Then the weather stayed. The
      meteorologists called it <i>an anomaly</i>, the government called it
      <i>temporary</i>, and the rain called it <i>home</i>. Somewhere along the way
      the rain turned sour &mdash; and the people caught out in it stopped being
      people.</p>
      <p class="body">They sealed the city before anyone thought to check who
      was still inside. So here you are: one survivor, one set of dry clothes,
      and a whole locked-down quarantine zone between you and rescue. The radio
      tower is silent. The satellite dish is in pieces. The dead are patient.</p>
      <p class="body">Rule one: <b>stay dry</b>. Rule two: <b>stay fed</b>. Rule
      three: there is no rule three. Anyone who tells you there's a rule three is
      trying to take your umbrella.</p>
      ${photo("shots/shot_flooded_cars.jpg", "Fig. 1 &mdash; Long-stay parking, now with added stay.", "tilt-l")}
      ${RUN}` });

    /* p4 — survivor gauges --------------------------------------------------- */
    P.push({ no: 4, html: `
      ${head("2", "Know Your Survivor")}
      <p class="body">Six numbers stand between you and the mud. Watch them the
      way the dead watch you: constantly.</p>
      <div class="gauges">
        <div class="gauge"><span class="g">Health</span><span class="d">Everything hurts you: teeth, hunger, thirst and the rain itself. Restore it with medical supplies, or sleep it off in a safe bed.</span></div>
        <div class="gauge"><span class="g">Stamina</span><span class="d">Sprinting, swinging and scrambling all drain it. A snack or a swig puts the spring back in your step.</span></div>
        <div class="gauge"><span class="g">Hunger</span><span class="d">Ticks down slowly but relentlessly. At zero, your stomach starts eating <i>you</i>. Don't let it.</span></div>
        <div class="gauge"><span class="g">Thirst</span><span class="d">Drains faster than hunger. Surrounded by water, none of it drinkable &mdash; the zone's little joke.</span></div>
        <div class="gauge"><span class="g">pH Meter</span><span class="d">Your skin's tolerance for the rain. It recovers under cover; at zero the rain starts burning.</span></div>
        <div class="gauge"><span class="g">Battery</span><span class="d">Powers your torch <i>and</i> your map. Both at once drains it double-quick. Darkness is cheaper &mdash; but pricier.</span></div>
      </div>
      ${photo("shots/shot_map_rain.jpg", "Fig. 2 &mdash; Map out, torch on: the battery pays for both.", "tilt-r")}
      ${RUN}` });

    /* p5 — actions ----------------------------------------------------------- */
    P.push({ no: 5, html: `
      ${head("3", "Survivor Actions", "bindings adjustable in options")}
      <table class="ctl">
        <tr><td>Move / Look</td><td>get where you're going, see what's coming</td></tr>
        <tr><td>Sprint</td><td>faster than walking, hungrier than walking</td></tr>
        <tr><td>Jump</td><td>for fences, gaps and dramatic exits</td></tr>
        <tr><td>Aim</td><td>steady the weapon in hand</td></tr>
        <tr><td>Fire / Use</td><td>shoot, swing, eat, drink or bandage &mdash; whatever is equipped</td></tr>
        <tr><td>Zoom</td><td>scoped weapons only &mdash; see trouble before it sees you</td></tr>
        <tr><td>Reload</td><td>an empty gun is a very short club</td></tr>
        <tr><td>Interact</td><td>doors, beds, vehicles, survivors in need</td></tr>
        <tr><td>Inventory</td><td>hold to rummage through your pack</td></tr>
        <tr><td>Torch</td><td>light, at the cost of battery</td></tr>
        <tr><td>Drop</td><td>leave an item behind &mdash; travel light, regret later</td></tr>
        <tr><td>Scoreboard</td><td>see how your fellow survivors are doing</td></tr>
      </table>
      ${photo("shots/shot_survivor_action.jpg", "Fig. 3 &mdash; Fire / Use, demonstrated. The Raven Handgun.", "tilt-l")}
      ${RUN}` });

    /* p6 — the rain ---------------------------------------------------------- */
    P.push({ no: 6, cls: "stained", html: `
      ${head("4", "The Rain")}
      <p class="body">The rain is the zone's landlord, and the rent is your
      skin. Out in the open, your <b>pH meter</b> falls. When it reads zero, the
      acid starts on your health &mdash; and it does not stop until you get a roof
      over your head.</p>
      <div class="warnbox" style="margin:.5em 0">
        <p class="body typewriter" style="text-align:center;margin:0">
        &ldquo;pH LEVEL ZERO &mdash; FIND SHELTER TO STOP ACID RAIN DAMAGE.&rdquo;<br>
        <span style="font-size:.85em;color:var(--ink-soft)">&mdash; the last message some survivors ever read properly</span></p>
      </div>
      <p class="body"><span class="lead">Shelter</span> is anything solid overhead:
      a doorway, a bus stop, an underpass, the roof of a stranger's caravan.
      Under cover, the drips stop and your meter breathes again. Sleeping in a
      bed passes the worst of it in comfort.</p>
      ${photo("shots/shot_umbrella_rain.jpg", "Fig. 4 &mdash; Sighted on the west bridge: a survivor doing it properly.", "tilt-r")}
      ${RUN}` });

    /* p7 — rain & kit --------------------------------------------------------- */
    P.push({ no: 7, cls: "stained", html: `
      ${head("5", "The Rain &amp; Your Kit")}
      <p class="body">The rain doesn't just want you &mdash; it wants your
      wardrobe. Every minute outside, your mask, jacket and boots quietly rot on
      your body. Gear with better <b>Rain Resistance</b> soaks through more
      slowly. Gear at zero durability is called <i>litter</i>.</p>
      <h2 class="rule">The Noble Sacrifice of the Umbrella</h2>
      <p class="body">Raise an umbrella and it takes <b>all</b> the rain-rot on
      itself: while it's up, your clothes are spared entirely. The umbrella,
      of course, is dying for you the whole time. When it finally gives out,
      observe a short silence, then find another. The zone is British enough
      that you're never far from one.</p>
      <h2 class="rule">Reading Material</h2>
      <p class="body">Certain journals help: <i>A Rain Walker's Journal</i> slows
      the soak on everything you wear, and the <i>pH Primer</i> hurries your meter
      back up between showers (see page 20).</p>
      <div class="fieldnote">The brolly is bait, shield, roof and walking stick.
      Whoever designed this zone's weather also stocked it with umbrellas.
      I choose to believe someone up there feels guilty. <b>&mdash; M.</b></div>
      ${RUN}` });

    /* p8-13 — armoury --------------------------------------------------------- */
    P.push({ no: 8, html: `
      ${head("6", "The Armoury", "handguns")}
      <p class="body">Six handguns, all named after birds, none of which can fly.
      Light, quick to raise, happiest indoors at unkind range.</p>
      ${RSZ_ORDER.handgun.map(spec).join("")}
      ${RUN}` });

    P.push({ no: 9, html: `
      ${head("6", "The Armoury", "rifles")}
      <p class="body">For the survivor who prefers their problems distant.
      Scoped, slow and deliberate &mdash; like the rain itself.</p>
      ${RSZ_ORDER.rifle.map(spec).join("")}
      ${RUN}` });

    P.push({ no: 10, html: `
      ${head("6", "The Armoury", "shotguns")}
      <p class="body">The close-quarters vote-of-no-confidence. Spread means
      never having to say &ldquo;I missed.&rdquo;</p>
      ${RSZ_ORDER.shotgun.map(spec).join("")}
      ${RUN}` });

    P.push({ no: 11, html: `
      ${head("6", "The Armoury", "crossbows")}
      <p class="body">Quiet, elegant, and unbothered by damp powder. One bolt at
      a time &mdash; make each one a considered opinion.</p>
      ${RSZ_ORDER.crossbow.map(spec).join("")}
      ${RUN}` });

    P.push({ no: 12, html: `
      ${head("6", "The Armoury", "umbrellas")}
      <p class="body">Yes, they're weapons. A firm swing discourages the living
      and the dead alike &mdash; note the two damage listings. And while raised,
      an umbrella shields your clothes from the rain entirely (page 7).</p>
      ${RSZ_ORDER.umbrella.map(spec).join("")}
      ${RUN}` });

    P.push({ no: 13, html: `
      ${head("6", "The Armoury", "ammunition")}
      <p class="body">Found in boxes small and large. Calibre must match the
      bird in hand &mdash; rifle rounds will not fit a Sparrow, however hard you
      push.</p>
      <div class="grid cols2">${RSZ_ORDER.ammo.map(gitem).join("")}</div>
      ${photo("shots/shot_armed_survivor.jpg", "Fig. 5 &mdash; A Bullfinch in hand is worth two in the supermarket.", "tilt-l")}
      <div class="fieldnote">Large boxes are worth the detour. Bullets weigh
      nothing and forgiveness weighs less. <b>&mdash; M.</b></div>
      ${RUN}` });

    /* p14-17 — outfitting ------------------------------------------------------ */
    P.push({ no: 14, html: `
      ${head("7", "Outfitting", "masks")}
      <p class="body">Named for insects, worn against worse. A good mask keeps
      the rain off your face and the teeth off your throat &mdash; check both the
      Rain and Armour listings.</p>
      <div class="grid cols2">${RSZ_ORDER.mask.map(gitem).join("")}</div>
      ${RUN}` });

    P.push({ no: 15, html: `
      ${head("7", "Outfitting", "clothes")}
      <p class="body">Twelve outfits, every one named after a duck &mdash; the
      only creatures in the zone still enjoying the weather. Dress for rain,
      then for teeth.</p>
      <div class="grid cols2">${RSZ_ORDER.jacket.map(gitem).join("")}</div>
      ${RUN}` });

    P.push({ no: 16, html: `
      ${head("7", "Outfitting", "boots")}
      <p class="body">Named after the great British hills, because that's what
      your feet will be climbing. Good boots shrug off puddles and put distance
      in your stride &mdash; watch the Stamina listing.</p>
      <div class="grid cols2">${RSZ_ORDER.boots.map(gitem).join("")}</div>
      ${RUN}` });

    P.push({ no: 17, html: `
      ${head("7", "Outfitting", "backpacks")}
      <p class="body">Named for Britain's wild mammals, all of whom carry less
      than you're about to. Capacity is the only statistic that matters when
      the supermarket is a four-mile swim away.</p>
      <div class="grid cols2">${RSZ_ORDER.backpack.map(gitem).join("")}</div>
      ${photo("shots/shot_backpack_walk.jpg", "Fig. 6 &mdash; Everything he owns, in the standard-issue Hedgehog.", "tilt-r")}
      ${RUN}` });

    /* p18-19 — provisions ------------------------------------------------------ */
    P.push({ no: 18, html: `
      ${head("8", "Provisions", "food")}
      <p class="body">The zone's cuisine is exclusively tinned, wrapped or
      freeze-dried, and all of it beats the alternative. Eating also puts some
      spring back in your legs.</p>
      <div class="grid cols2">${RSZ_ORDER.food.map(gitem).join("")}</div>
      ${photo("shots/shot_looting.jpg", "Fig. 7 &mdash; Lunch, somewhere in aisle three.", "tilt-l")}
      ${RUN}` });

    P.push({ no: 19, html: `
      ${head("8", "Provisions", "drink &amp; first aid")}
      <h2 class="rule">Drink</h2>
      <div class="grid cols2">${RSZ_ORDER.drink.map(gitem).join("")}</div>
      <h2 class="rule">First Aid</h2>
      <div class="grid cols2">${RSZ_ORDER.medical.map(gitem).join("")}</div>
      <div class="fieldnote">Small tins for small scrapes, large for the stories
      you'll tell later. Antibiotics don't care how brave you were.
      <b>&mdash; M.</b></div>
      ${RUN}` });

    /* p20-21 — journals -------------------------------------------------------- */
    const J = RSZ_ORDER.journal;
    P.push({ no: 20, html: `
      ${head("9", "Survivor's Journals")}
      <p class="body">Other survivors wrote down what they learned. Carry a
      journal and its wisdom works for you &mdash; but each is a fragile thing
      that wears out <b>every time its advice is used</b>. How long one lasts
      depends on the advice: a volume consulted with every stride ages
      differently from one opened once a storm. When it finally falls apart,
      the wisdom goes with it. Keep a spare eye out for second copies.</p>
      ${J.slice(0, 7).map(jitem).join("")}
      ${RUN}` });

    P.push({ no: 21, html: `
      ${head("9", "Survivor's Journals", "continued")}
      ${J.slice(7).map(jitem).join("")}
      <div style="width:86%; margin:0 auto">${photo("shots/shot_horse_umbrella.jpg", "Fig. 8 &mdash; A graduate of <i>Stubborn Beasts</i>, with umbrella, going places.", "tilt-r")}</div>
      ${RUN}` });

    /* p22-23 — missions --------------------------------------------------------- */
    P.push({ no: 22, html: `
      ${head("10", "Missions", "locked doors")}
      <p class="body">Some doors in the zone only open for the right piece of
      plastic. The former owners no longer need them. Probably.</p>
      <div class="grid cols3" style="margin-bottom:3%">${["PoliceKeycardBP", "MilitaryIDBP", "BunkerKeycardBP"].map(gitem).join("")}</div>
      <p class="body">The police station armoury, the military base and the
      secret bunker are all waiting behind their respective cards. What's inside
      is between you and the door.</p>
      <div class="mcards">
        <div class="mcard"><img src="assets/ui/mission_police.png" alt="Police station mission card"></div>
        <div class="mcard"><img src="assets/ui/mission_military.png" alt="Military base mission card"></div>
        <div class="mcard"><img src="assets/ui/mission_bunker.png" alt="Bunker mission card"></div>
        <div class="mcard"><img src="assets/ui/mission_radiotower.png" alt="Radio tower mission card"></div>
      </div>
      ${RUN}` });

    P.push({ no: 23, html: `
      ${head("10", "Missions", "signals &amp; survivors")}
      <p class="body">The zone's radio tower and satellite dish went quiet a
      long time ago. Their missing parts didn't walk off by themselves &mdash;
      but they can walk back with you.</p>
      <div class="grid cols2" style="margin-bottom:3%">${["RadioTowerPartBP", "SatelliteDishPartBP"].map(gitem).join("")}</div>
      <p class="body">You are not the last soul out here. Some survivors need
      food, some need medicine, one wants a handgun and no questions. Helping
      them costs you supplies. Not helping them costs something harder to
      restock.</p>
      <div class="mcards">
        <div class="mcard"><img src="assets/ui/mission_satellitedish.png" alt="Satellite dish mission card"></div>
        <div class="mcard"><img src="assets/ui/mission_survivor_food.png" alt="Survivor food request card"></div>
        <div class="mcard"><img src="assets/ui/mission_survivor_medical.png" alt="Survivor medical request card"></div>
        <div class="mcard"><img src="assets/ui/mission_survivor_handgun.png" alt="Survivor handgun request card"></div>
      </div>
      ${RUN}` });

    /* p24-25 — the zone (map spread) --------------------------------------------- */
    const GAZ = [
      ["Abandoned Mine", "dark, deep, exactly as advertised"],
      ["Southside Airport", "all flights cancelled, permanently"],
      ["Secret Bunker", "the worst-kept secret in the zone"],
      ["Caravan Park", "holiday homes, extended season"],
      ["City Car Park", "spaces available"],
      ["City Cathedral", "the roof still keeps the rain out"],
      ["Deluxe Cinema", "one film, forever"],
      ["Isolated Farmhouse", "isolation: no longer a selling point"],
      ["Residential Flats", "neighbours quieter than ever"],
      ["Hailes Appartments", "luxury living, some wear"],
      ["Abandoned Hotel", "vacancies"],
      ["South East Industrial", "heavy machinery, light security"],
      ["Island House", "the estate agent called it 'characterful'"],
      ["Lakeside Cottages", "waterfront views on all sides now"],
      ["Military Base", "requires ID (see page 22)"],
    ];
    const GAZ2 = [
      ["Old Mill", "grinding to a halt since the incident"],
      ["South Petrol Station", "pumps dry, shelves maybe not"],
      ["East Petrol Station", "see above, but east"],
      ["North Petrol Station", "the scenic one"],
      ["Police Station", "keycard required (see page 22)"],
      ["Cooling Towers", "impressively dry inside"],
      ["Railway Depot", "end of the line"],
      ["City Railway Station", "replacement bus service suspended"],
      ["Radio Tower", "silent, fixable (see page 23)"],
      ["Deserted High School", "term ended early"],
      ["Shopping Mall", "everything must go; everything went"],
      ["Destroyed Skyscraper", "short-stay accommodation"],
      ["Overgrown Stadium", "the pitch has never looked greener"],
      ["Ransacked Supermarket", "check aisle three (fig. 7)"],
      ["Underground Station", "mind the gap, and the rest"],
    ];
    P.push({ no: 24, html: `
      ${head("11", "The Zone", "west")}
      <div class="mapwrap"><img src="assets/art/map.jpg" alt="Quarantine zone map, western half"></div>
      ${gaz(GAZ)}
      ${RUN}` });
    P.push({ no: 25, html: `
      ${head("11", "The Zone", "east")}
      <div class="mapwrap"><img src="assets/art/map.jpg" alt="Quarantine zone map, eastern half"></div>
      ${gaz(GAZ2)}
      ${RUN}` });

    /* p26 — the undead ----------------------------------------------------------- */
    P.push({ no: 26, cls: "stained", html: `
      ${head("12", "The Undead", "field notes")}
      <p class="body typewriter">Compiled from survivor accounts. Entries the
      censor could not verify have been struck out for your safety.</p>
      <p class="body">They were people once, before the rain got into them. They
      hunt whoever is nearest &mdash; in the zone, that is usually you. They do
      not tire, do not shelter, and do not care what the umbrella cost.</p>
      <p class="body">A firm blow can stagger one mid-lunge; a firm anything can
      finish the job. They go down like anyone else, just less reluctantly.
      Survivors report the dry ones move <span class="redacted">redacted
      redacted</span>, while the rain-soaked <span class="redacted">redacted
      entirely</span>. <span class="redacted">Absolutely not printing that.</span></p>
      <div class="cols">
        <div>${photo("shots/shot_zombie_attack.jpg", "Fig. 9 &mdash; Too close. Turn the page faster.", "tilt-l")}</div>
        <div>${photo("shots/shot_zombie_pair.jpg", "Fig. 10 &mdash; Field sketch: the dry variety.", "tilt-r")}</div>
      </div>
      <div class="fieldnote">Whatever you're holding, hold it tighter.
      <b>&mdash; M.</b></div>
      ${RUN}` });

    /* p27 — multiplayer ------------------------------------------------------------ */
    P.push({ no: 27, html: `
      ${head("13", "Surviving Together")}
      <p class="body">The zone takes lone heroes first. Team up with your
      fellow survivors and you share the map, the loot, the vehicles and the
      blame. One survivor holds the brolly, one holds the shotgun &mdash;
      civilisation, rebuilt.</p>
      <p class="body"><span class="lead">The wave.</span> Meet a stranger, open
      the messages menu, and <b>wave</b>. If they wave back, you are officially
      friends: each other's name tags appear across the whole zone, however far
      apart you roam &mdash; and your weapons <b>refuse to harm one another</b>,
      no matter how badly you aim. Friendship, as a game mechanic. As far as we
      know, this is the only zone where it's bulletproof.</p>
      <p class="body"><span class="lead">A word on aim.</span> Until you've waved,
      your weapons do not check affiliation before landing. Strangers take
      damage like anyone else, and acquaintances have ended over less than a
      misplaced Eagle round. Check your target &mdash; or better, wave first.</p>
      <p class="body"><span class="lead">Sharing the load.</span> Supplies handed to
      survivors in need (page 23) come out of your pack. Split the shopping list
      before you set out, like any sensible doomed expedition.</p>
      <p class="body"><span class="lead">The unsinkable session.</span> If the host
      has to leave &mdash; rescue, rage or bedtime &mdash; Rain Station Z's
      bespoke, custom-written host migration hands the whole zone to another player
      mid-storm. The world, the loot and the argument about who wasted the
      shotgun shells all carry on without a hitch.</p>
      <p class="body"><span class="lead">Say it out loud.</span> Free text chat,
      with a full on-screen keyboard (see page 29). Coordinate, negotiate,
      apologise.</p>
      ${photo("shots/shot_two_survivors.jpg", "Fig. 11 &mdash; Matching outfits: intimidation or friendship. Often both.", "tilt-l")}
      ${RUN}` });

    /* p28 — photo mode ---------------------------------------------------------------- */
    P.push({ no: 28, html: `
      ${head("14", "Photo Mode", "practice mode only")}
      <p class="body">The zone is hideous and beautiful in roughly equal
      measure, so the practice expedition kit includes a full camera rig: a
      free-roaming lens and eleven ways to grade the end of the world.</p>
      <div class="warnbox" style="margin:.4em 0">
        <p class="body typewriter" style="text-align:center;margin:0">
        AVAILABLE IN SINGLE-PLAYER <b>PRACTICE MODE</b> ONLY.<br>
        <span style="font-size:.85em;color:var(--ink-soft)">In multiplayer the free camera belongs to the spectator view
        &mdash; no sliders, no posing, just watching your friends manage without you.</span></p>
      </div>
      <div class="cols" style="font-family:'Special Elite',monospace; font-size:11px; line-height:1.5">
        <div>FIELD OF VIEW &mdash; wide angle to telephoto<br>
        FOCUS DISTANCE &mdash; choose what deserves sharpness<br>
        DEPTH OF FIELD &mdash; blur everything you can't fix<br>
        SATURATION &mdash; from postcard to despair<br>
        CONTRAST &mdash; deepen the gloom, or flatten it<br>
        WHITE BALANCE &mdash; warm the apocalypse up a touch</div>
        <div>LENS RAIN &mdash; droplets on the glass, on demand<br>
        BLOOM &mdash; make the torchlight sing<br>
        LENS FLARE &mdash; pretend the sun still visits<br>
        VIGNETTE &mdash; darkness closing in, artistically<br>
        FILM GRAIN &mdash; instant 35mm<br>&nbsp;</div>
      </div>
      <div class="cols">
        <div>${photo("shots/shot_photomode_bw.jpg", "Fig. 12 &mdash; Vignette up, saturation gone.", "tilt-l")}</div>
        <div>${photo("shots/shot_photomode_blue.jpg", "Fig. 13 &mdash; The same street, feeling blue.", "tilt-r")}</div>
      </div>
      ${RUN}` });

    /* p29 — field capabilities ---------------------------------------------------------- */
    const FEATS = [
      ["One open-world quarantine zone", "thirty named locations; sealed at the perimeter, open everywhere inside"],
      ["Online multiplayer", "shared world, shared loot, shared blame"],
      ["Bespoke host migration", "custom-written: if the host leaves, the session simply carries on under new management"],
      ["Free text chat", "a full on-screen keyboard &mdash; coordinate, trade, apologise"],
      ["The wave", "wave at a stranger; if they wave back, you're friends &mdash; name tags across the zone, weapons that refuse to hurt each other"],
      ["Practice mode", "the whole zone to yourself, plus the camera rig (page 28)"],
      ["Photo mode", "eleven sliders between you and a gallery piece"],
      ["Rideable beasts", "the zone's horses are stubborn but negotiable"],
      ["Weather with intent", "acid rain that hunts your health, your wardrobe and your umbrella"],
      ["Day and night", "bring a torch; budget for batteries"],
      ["A hundred-plus items", "birds, ducks, insects, mammals and hills to collect"],
      ["Survivors in need", "help them, arm them, feed them &mdash; or live with it"],
    ];
    P.push({ no: 29, html: `
      ${head("15", "Field Capabilities", "back of the box")}
      <div style="margin:.4em 0 .8em">${FEATS.map(([f, d]) =>
        `<div class="gauge"><span class="g" style="width:31%">&#9745; ${f}</span><span class="d">${d}</span></div>`).join("")}
      </div>
      ${photo("ui/keyboard.png", "Fig. 14 &mdash; The zone's full QWERTY &mdash; note the wave button, bottom left. Mind your language; the dead are listening.", "tilt-l")}
      ${RUN}` });

    /* p30 — notes -------------------------------------------------------------------- */
    P.push({ no: 30, html: `
      ${head("&#9998;", "Field Notes", "your page")}
      <div class="ruled">
        <span style="position:absolute; top:0; left:2%">days without incident:&nbsp;&nbsp;0</span>
        <div class="coffeering"></div>
      </div>
      ${RUN}` });

    /* p31 — credits -------------------------------------------------------------------- */
    P.push({ no: 31, cls: "stained", html: `
      ${head("&#10045;", "Credits")}
      <div style="text-align:center; margin-top:6%">
        <p class="typewriter" style="letter-spacing:.25em; font-size:13px">A GAME BY</p>
        <p style="font-family:'Oswald',sans-serif; font-weight:700; text-transform:uppercase; font-size:28px; letter-spacing:.08em">Wobbly Tooth Limited</p>
        <p class="typewriter" style="margin-top:4%; font-size:12px; color:var(--ink-soft)">
          wobbly-tooth.com</p>
        <div style="margin:8% auto; width:50%; border-top:1px solid var(--ink-soft)"></div>
        <p class="body" style="text-align:center">This handbook was assembled from
        genuine zone survey data, eyewitness testimony and the marginalia of
        survivor M., whereabouts unknown, umbrella presumed raised.</p>
        <p class="body" style="text-align:center">All weapon evaluations are
        relative to their class. No numbers were harmed &mdash; or printed &mdash;
        in the making of this manual.</p>
        <p class="typewriter" style="margin-top:6%; font-size:11px; color:var(--ink-soft)">
          &copy; Wobbly Tooth Limited. All rights reserved.<br>
          Printed inside the zone. Dried twice.</p>
      </div>
      ${RUN}` });

    /* BACK COVER ------------------------------------------------------------------------ */
    P.push({ no: null, cls: "cover", html: `
      <div class="art" style="margin-top:10%">${photo("shots/shot_horse_night.jpg", "")}</div>
      <p style="font-family:'Oswald',sans-serif; font-weight:600; text-transform:uppercase; letter-spacing:.3em; font-size:19px; margin:6% 0 2%">Keep dry. Don't die.</p>
      <p class="typewriter" style="font-size:11px; color:#c8bea4">wobbly-tooth.com/RainStationZ</p>
      <div class="badges" style="margin-bottom:2%">
        <span class="badge">Steam</span>
        <span class="badge">PlayStation 5</span>
        <span class="badge">Nintendo Switch</span>
      </div>
      <div class="barcode"></div>
      <div class="barcode-num">5 014416 000000</div>` });

    return P;
  }

  /* ------------------------------------------------------ pick edition -- */

  const helpers = { photo, head, spec, gitem, jitem, gaz, RUN };
  const P = (LANG === "ja" && window.RSZ_JA_BUILD)
    ? window.RSZ_JA_BUILD(helpers)
    : buildPagesEN();

  if (LANG === "ja") {
    document.documentElement.lang = "ja";
    document.body.classList.add("lang-ja");
    document.title = "レインステーションZ ― サバイバルハンドブック";
  }
  const activeLangLink = document.querySelector('#langtab a[data-lang="' + LANG + '"]');
  if (activeLangLink) activeLangLink.classList.add("active");

  const WORD = LANG === "ja"
    ? { page: "ページ ", cover: "表紙", back: "裏表紙" }
    : { page: "PAGE ", cover: "COVER", back: "BACK COVER" };

  /* -------------------------------------------------------------- engine -- */

  const spreadEl = document.getElementById("spread");
  const prevBtn = document.getElementById("prev");
  const nextBtn = document.getElementById("next");
  const tabEl = document.getElementById("pagetab");

  const mobileQuery = window.matchMedia("(max-width: 760px), (max-aspect-ratio: 5/6)");
  let views = [];
  let cur = 0;

  function buildViews() {
    views = [];
    if (mobileQuery.matches) {
      for (let i = 0; i < P.length; i++) views.push([i]);
    } else {
      views.push([0]);                       // front cover alone
      for (let i = 1; i < P.length - 1; i += 2) {
        views.push(i + 1 < P.length - 1 ? [i, i + 1] : [i]);
      }
      views.push([P.length - 1]);            // back cover alone
    }
  }

  function pageDiv(idx, side) {
    const p = P[idx];
    const d = document.createElement("div");
    d.className = "page " + side + (p.cls ? " " + p.cls : "");
    d.innerHTML = p.html + (p.no !== null ?
      `<div class="pageno">&mdash; ${p.no} &mdash;</div>` : "");
    return d;
  }

  function render(dir) {
    const v = views[cur];
    spreadEl.classList.toggle("single", v.length === 1 && !mobileQuery.matches);
    spreadEl.innerHTML = "";
    v.forEach((pi, k) => {
      const side = v.length === 1 ? "right single-pg" : (k === 0 ? "left" : "right");
      spreadEl.appendChild(pageDiv(pi, side));
    });
    if (v.length === 2) {
      const s1 = document.createElement("div"); s1.className = "staple s1";
      const s2 = document.createElement("div"); s2.className = "staple s2";
      spreadEl.appendChild(s1); spreadEl.appendChild(s2);
    }
    prevBtn.disabled = cur === 0;
    nextBtn.disabled = cur === views.length - 1;
    const nos = v.map(pi => P[pi].no).filter(n => n !== null);
    tabEl.textContent = nos.length ? WORD.page + nos.join(" – ") :
      (v.includes(0) ? WORD.cover : (v.includes(P.length - 1) ? WORD.back : ""));
    spreadEl.style.setProperty("--turn-dx", (dir < 0 ? -14 : 14) + "px");
    spreadEl.classList.remove("turning");
    void spreadEl.offsetWidth;               // restart animation
    spreadEl.classList.add("turning");
    fit();
  }

  function go(delta) {
    const n = Math.min(Math.max(cur + delta, 0), views.length - 1);
    if (n !== cur) { cur = n; render(delta); }
  }

  function gotoPageNo(no) {
    const idx = P.findIndex(p => p.no === no);
    if (idx < 0) return;
    const vi = views.findIndex(v => v.includes(idx));
    if (vi >= 0) { const d = vi > cur ? 1 : -1; cur = vi; render(d); }
  }

  prevBtn.addEventListener("click", () => go(-1));
  nextBtn.addEventListener("click", () => go(1));
  document.addEventListener("keydown", e => {
    if (e.key === "ArrowLeft" || e.key === "PageUp") go(-1);
    if (e.key === "ArrowRight" || e.key === "PageDown" || e.key === " ") go(1);
    if (e.key === "Home") { cur = 0; render(-1); }
    if (e.key === "End") { cur = views.length - 1; render(1); }
  });
  spreadEl.addEventListener("click", e => {
    const toc = e.target.closest("[data-goto]");
    if (toc) { gotoPageNo(parseInt(toc.dataset.goto, 10)); return; }
  });
  // swipe for mobile
  let touchX = null;
  spreadEl.addEventListener("touchstart", e => { touchX = e.touches[0].clientX; }, { passive: true });
  spreadEl.addEventListener("touchend", e => {
    if (touchX === null) return;
    const dx = e.changedTouches[0].clientX - touchX;
    if (Math.abs(dx) > 55) go(dx < 0 ? 1 : -1);
    touchX = null;
  }, { passive: true });

  function fit() {
    if (mobileQuery.matches) { spreadEl.style.transform = ""; return; }
    const s = Math.min(
      (window.innerWidth - 118) / spreadEl.offsetWidth,
      (window.innerHeight - 58) / spreadEl.offsetHeight,
      1.18);
    spreadEl.style.transform = "scale(" + s + ")";
  }
  window.addEventListener("resize", fit);

  mobileQuery.addEventListener("change", () => {
    const firstPage = views[cur][0];
    buildViews();
    cur = Math.max(views.findIndex(v => v.includes(firstPage)), 0);
    render(1);
  });

  buildViews();
  render(1);
})();
