// GENERATED by tools/build_data.py — do not edit by hand.
// Stats are qualitative tiers derived per-category from the CDO export.
const RSZ_ITEMS = {
 "ColtBP": {
  "name": "Sparrow Handgun",
  "icon": "icon_colt.png",
  "cat": "handgun",
  "stats": [
   [
    "Damage",
    "Very Low"
   ],
   [
    "Durability",
    "Very High"
   ],
   [
    "Range",
    "Very Low"
   ],
   [
    "Accuracy",
    "Very Low"
   ],
   [
    "Clip Size",
    "Low"
   ],
   [
    "Fire Rate",
    "Low"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30b9\u30d1\u30ed\u30fc\u30fb\u30cf\u30f3\u30c9\u30ac\u30f3"
 },
 "ColtAltBP": {
  "name": "Magpie Handgun",
  "icon": "icon_colt_alt.png",
  "cat": "handgun",
  "stats": [
   [
    "Damage",
    "Very Low"
   ],
   [
    "Durability",
    "Very High"
   ],
   [
    "Range",
    "Very Low"
   ],
   [
    "Accuracy",
    "Low"
   ],
   [
    "Clip Size",
    "Low"
   ],
   [
    "Fire Rate",
    "Low"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30de\u30b0\u30d1\u30a4\u30fb\u30cf\u30f3\u30c9\u30ac\u30f3"
 },
 "GlockBP": {
  "name": "Chiffchaff Handgun",
  "icon": "icon_glock.png",
  "cat": "handgun",
  "stats": [
   [
    "Damage",
    "Low"
   ],
   [
    "Durability",
    "High"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "Low"
   ],
   [
    "Clip Size",
    "High"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30c1\u30d5\u30c1\u30e3\u30d5\u30fb\u30cf\u30f3\u30c9\u30ac\u30f3"
 },
 "GlockAltBP": {
  "name": "Robin Handgun",
  "icon": "icon_glock_alt.png",
  "cat": "handgun",
  "stats": [
   [
    "Damage",
    "Low"
   ],
   [
    "Durability",
    "Moderate"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "High"
   ],
   [
    "Clip Size",
    "High"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30ed\u30d3\u30f3\u30fb\u30cf\u30f3\u30c9\u30ac\u30f3"
 },
 "DeagleBP": {
  "name": "Eagle Handgun",
  "icon": "icon_deagle.png",
  "cat": "handgun",
  "stats": [
   [
    "Damage",
    "Very High"
   ],
   [
    "Durability",
    "Low"
   ],
   [
    "Range",
    "Very High"
   ],
   [
    "Accuracy",
    "High"
   ],
   [
    "Clip Size",
    "Low"
   ],
   [
    "Fire Rate",
    "High"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30a4\u30fc\u30b0\u30eb\u30fb\u30cf\u30f3\u30c9\u30ac\u30f3"
 },
 "DeagleAltBP": {
  "name": "Raven Handgun",
  "icon": "icon_deagle_alt.png",
  "cat": "handgun",
  "stats": [
   [
    "Damage",
    "Very High"
   ],
   [
    "Durability",
    "Very Low"
   ],
   [
    "Range",
    "Very High"
   ],
   [
    "Accuracy",
    "Very High"
   ],
   [
    "Clip Size",
    "Low"
   ],
   [
    "Fire Rate",
    "High"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30ec\u30a4\u30f4\u30f3\u30fb\u30cf\u30f3\u30c9\u30ac\u30f3"
 },
 "CrossbowOneBP": {
  "name": "Swift Crossbow",
  "icon": "icon_crossbowone.png",
  "cat": "crossbow",
  "stats": [
   [
    "Damage",
    "Very Low"
   ],
   [
    "Durability",
    "Very High"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "Low"
   ],
   [
    "Fire Rate",
    "Very Low"
   ],
   [
    "Reload",
    "Very Low"
   ],
   [
    "Zoom",
    "Very Low"
   ]
  ],
  "name_ja": "\u30b9\u30a6\u30a3\u30d5\u30c8\u30fb\u30af\u30ed\u30b9\u30dc\u30a6"
 },
 "CrossbowOneAltBP": {
  "name": "Falcon Crossbow",
  "icon": "icon_crossbowone_alt.png",
  "cat": "crossbow",
  "stats": [
   [
    "Damage",
    "Very Low"
   ],
   [
    "Durability",
    "Very High"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "Low"
   ],
   [
    "Fire Rate",
    "Very Low"
   ],
   [
    "Reload",
    "Very Low"
   ],
   [
    "Zoom",
    "Low"
   ]
  ],
  "name_ja": "\u30d5\u30a1\u30eb\u30b3\u30f3\u30fb\u30af\u30ed\u30b9\u30dc\u30a6"
 },
 "CrossbowTwoBP": {
  "name": "Merlin Crossbow",
  "icon": "icon_crossbowtwo.png",
  "cat": "crossbow",
  "stats": [
   [
    "Damage",
    "Moderate"
   ],
   [
    "Durability",
    "High"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "Moderate"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ],
   [
    "Zoom",
    "Moderate"
   ]
  ],
  "name_ja": "\u30de\u30fc\u30ea\u30f3\u30fb\u30af\u30ed\u30b9\u30dc\u30a6"
 },
 "CrossbowTwoAltBP": {
  "name": "Kestrel Crossbow",
  "icon": "icon_crossbowtwo_alt.png",
  "cat": "crossbow",
  "stats": [
   [
    "Damage",
    "Moderate"
   ],
   [
    "Durability",
    "Moderate"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "High"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ],
   [
    "Zoom",
    "High"
   ]
  ],
  "name_ja": "\u30b1\u30b9\u30c8\u30ec\u30eb\u30fb\u30af\u30ed\u30b9\u30dc\u30a6"
 },
 "CrossbowThreeBP": {
  "name": "Razorbill Crossbow",
  "icon": "icon_crossbowthree.png",
  "cat": "crossbow",
  "stats": [
   [
    "Damage",
    "Very High"
   ],
   [
    "Durability",
    "Low"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "High"
   ],
   [
    "Fire Rate",
    "Very High"
   ],
   [
    "Reload",
    "Very High"
   ],
   [
    "Zoom",
    "Very High"
   ]
  ],
  "name_ja": "\u30ec\u30a4\u30b6\u30fc\u30d3\u30eb\u30fb\u30af\u30ed\u30b9\u30dc\u30a6"
 },
 "CrossbowThreeAltBP": {
  "name": "Sparrowhawk Crossbow",
  "icon": "icon_crossbowthree_alt.png",
  "cat": "crossbow",
  "stats": [
   [
    "Damage",
    "Very High"
   ],
   [
    "Durability",
    "Very Low"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Fire Rate",
    "Very High"
   ],
   [
    "Reload",
    "Very High"
   ],
   [
    "Zoom",
    "Very High"
   ]
  ],
  "name_ja": "\u30b9\u30d1\u30ed\u30a6\u30db\u30fc\u30af\u30fb\u30af\u30ed\u30b9\u30dc\u30a6"
 },
 "RifleOneBP": {
  "name": "Starling Rifle",
  "icon": "icon_rifleone.png",
  "cat": "rifle",
  "stats": [
   [
    "Damage",
    "Very Low"
   ],
   [
    "Durability",
    "Very High"
   ],
   [
    "Range",
    "Very Low"
   ],
   [
    "Accuracy",
    "Low"
   ],
   [
    "Clip Size",
    "Moderate"
   ],
   [
    "Fire Rate",
    "High"
   ],
   [
    "Reload",
    "Moderate"
   ],
   [
    "Zoom",
    "Very Low"
   ]
  ],
  "name_ja": "\u30b9\u30bf\u30fc\u30ea\u30f3\u30b0\u30fb\u30e9\u30a4\u30d5\u30eb"
 },
 "RifleOneAltBP": {
  "name": "Kingfisher Rifle",
  "icon": "icon_rifleone_alt.png",
  "cat": "rifle",
  "stats": [
   [
    "Damage",
    "Very Low"
   ],
   [
    "Durability",
    "Very High"
   ],
   [
    "Range",
    "Very Low"
   ],
   [
    "Accuracy",
    "Low"
   ],
   [
    "Clip Size",
    "Moderate"
   ],
   [
    "Fire Rate",
    "High"
   ],
   [
    "Reload",
    "Moderate"
   ],
   [
    "Zoom",
    "Low"
   ]
  ],
  "name_ja": "\u30ad\u30f3\u30b0\u30d5\u30a3\u30c3\u30b7\u30e3\u30fc\u30fb\u30e9\u30a4\u30d5\u30eb"
 },
 "RifleTwoBP": {
  "name": "Redstart Rifle",
  "icon": "icon_rifletwo.png",
  "cat": "rifle",
  "stats": [
   [
    "Damage",
    "Moderate"
   ],
   [
    "Durability",
    "High"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "Low"
   ],
   [
    "Clip Size",
    "Moderate"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ],
   [
    "Zoom",
    "Moderate"
   ]
  ],
  "name_ja": "\u30ec\u30c3\u30c9\u30b9\u30bf\u30fc\u30c8\u30fb\u30e9\u30a4\u30d5\u30eb"
 },
 "RifleTwoAltBP": {
  "name": "Yellowhammer Rifle",
  "icon": "icon_rifletwo_alt.png",
  "cat": "rifle",
  "stats": [
   [
    "Damage",
    "Moderate"
   ],
   [
    "Durability",
    "Moderate"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "Low"
   ],
   [
    "Clip Size",
    "Moderate"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ],
   [
    "Zoom",
    "High"
   ]
  ],
  "name_ja": "\u30a4\u30a8\u30ed\u30fc\u30cf\u30f3\u30de\u30fc\u30fb\u30e9\u30a4\u30d5\u30eb"
 },
 "RifleThreeBP": {
  "name": "Greenfinch Rifle",
  "icon": "icon_riflethree.png",
  "cat": "rifle",
  "stats": [
   [
    "Damage",
    "Very High"
   ],
   [
    "Durability",
    "Low"
   ],
   [
    "Range",
    "Very High"
   ],
   [
    "Accuracy",
    "High"
   ],
   [
    "Clip Size",
    "Moderate"
   ],
   [
    "Fire Rate",
    "Low"
   ],
   [
    "Reload",
    "Moderate"
   ],
   [
    "Zoom",
    "Very High"
   ]
  ],
  "name_ja": "\u30b0\u30ea\u30fc\u30f3\u30d5\u30a3\u30f3\u30c1\u30fb\u30e9\u30a4\u30d5\u30eb"
 },
 "RifleThreeAltBP": {
  "name": "Bluebird Rifle",
  "icon": "icon_riflethree_alt.png",
  "cat": "rifle",
  "stats": [
   [
    "Damage",
    "Very High"
   ],
   [
    "Durability",
    "Very Low"
   ],
   [
    "Range",
    "Very High"
   ],
   [
    "Clip Size",
    "Moderate"
   ],
   [
    "Fire Rate",
    "Low"
   ],
   [
    "Reload",
    "Moderate"
   ],
   [
    "Zoom",
    "Very High"
   ]
  ],
  "name_ja": "\u30d6\u30eb\u30fc\u30d0\u30fc\u30c9\u30fb\u30e9\u30a4\u30d5\u30eb"
 },
 "ShotgunOneBP": {
  "name": "Warbler Shotgun",
  "icon": "icon_shotgunone.png",
  "cat": "shotgun",
  "stats": [
   [
    "Damage",
    "Very Low"
   ],
   [
    "Durability",
    "Very High"
   ],
   [
    "Range",
    "Low"
   ],
   [
    "Accuracy",
    "Very Low"
   ],
   [
    "Clip Size",
    "Low"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30a6\u30a9\u30fc\u30d6\u30e9\u30fc\u30fb\u30b7\u30e7\u30c3\u30c8\u30ac\u30f3"
 },
 "ShotgunOneAltBP": {
  "name": "Buzzard Shotgun",
  "icon": "icon_shotgunone_alt.png",
  "cat": "shotgun",
  "stats": [
   [
    "Damage",
    "Low"
   ],
   [
    "Durability",
    "Very High"
   ],
   [
    "Range",
    "Low"
   ],
   [
    "Accuracy",
    "Low"
   ],
   [
    "Clip Size",
    "Low"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30ce\u30b9\u30ea\u30fb\u30b7\u30e7\u30c3\u30c8\u30ac\u30f3"
 },
 "ShotgunTwoBP": {
  "name": "Bullfinch Shotgun",
  "icon": "icon_shotguntwo.png",
  "cat": "shotgun",
  "stats": [
   [
    "Damage",
    "Moderate"
   ],
   [
    "Durability",
    "Moderate"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "Moderate"
   ],
   [
    "Clip Size",
    "High"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30d6\u30eb\u30d5\u30a3\u30f3\u30c1\u30fb\u30b7\u30e7\u30c3\u30c8\u30ac\u30f3"
 },
 "ShotgunTwoAltBP": {
  "name": "Jackdaw Shotgun",
  "icon": "icon_shotguntwo_alt.png",
  "cat": "shotgun",
  "stats": [
   [
    "Damage",
    "High"
   ],
   [
    "Durability",
    "Moderate"
   ],
   [
    "Range",
    "Moderate"
   ],
   [
    "Accuracy",
    "High"
   ],
   [
    "Clip Size",
    "High"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30b8\u30e3\u30c3\u30af\u30c9\u30a6\u30fb\u30b7\u30e7\u30c3\u30c8\u30ac\u30f3"
 },
 "ShotgunThreeBP": {
  "name": "Harrier Shotgun",
  "icon": "icon_shotgunthree.png",
  "cat": "shotgun",
  "stats": [
   [
    "Damage",
    "Very High"
   ],
   [
    "Durability",
    "Low"
   ],
   [
    "Range",
    "High"
   ],
   [
    "Accuracy",
    "Very High"
   ],
   [
    "Clip Size",
    "Low"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30cf\u30ea\u30a2\u30fc\u30fb\u30b7\u30e7\u30c3\u30c8\u30ac\u30f3"
 },
 "ShotgunThreeAltBP": {
  "name": "Vulture Shotgun",
  "icon": "icon_shotgunthree_alt.png",
  "cat": "shotgun",
  "stats": [
   [
    "Damage",
    "Very High"
   ],
   [
    "Durability",
    "Very Low"
   ],
   [
    "Range",
    "High"
   ],
   [
    "Accuracy",
    "Very High"
   ],
   [
    "Clip Size",
    "Low"
   ],
   [
    "Fire Rate",
    "Moderate"
   ],
   [
    "Reload",
    "Moderate"
   ]
  ],
  "name_ja": "\u30f4\u30a1\u30eb\u30c1\u30e3\u30fc\u30fb\u30b7\u30e7\u30c3\u30c8\u30ac\u30f3"
 },
 "AmmoCrossbowBP": {
  "name": "Crossbow Ammo",
  "icon": "icon_ammo_crossbow.png",
  "cat": "ammo",
  "stats": [],
  "name_ja": "\u30af\u30ed\u30b9\u30dc\u30a6\u306e\u5f3e"
 },
 "AmmoCrossbowLargeBP": {
  "name": "Crossbow Ammo (large)",
  "icon": "icon_ammo_crossbow.png",
  "cat": "ammo",
  "stats": [],
  "name_ja": "\u30af\u30ed\u30b9\u30dc\u30a6\u306e\u5f3e (\u5927)"
 },
 "AmmoHandgunBP": {
  "name": "Handgun Ammo",
  "icon": "icon_ammo_handgun.png",
  "cat": "ammo",
  "stats": [],
  "name_ja": "\u30cf\u30f3\u30c9\u30ac\u30f3\u306e\u5f3e"
 },
 "AmmoHandgunLargeBP": {
  "name": "Handgun Ammo (large)",
  "icon": "icon_ammo_handgun.png",
  "cat": "ammo",
  "stats": [],
  "name_ja": "\u30cf\u30f3\u30c9\u30ac\u30f3\u306e\u5f3e (\u5927)"
 },
 "AmmoRifleBP": {
  "name": "Rifle Ammo",
  "icon": "icon_ammo_rifle.png",
  "cat": "ammo",
  "stats": [],
  "name_ja": "\u30e9\u30a4\u30d5\u30eb\u306e\u5f3e"
 },
 "AmmoRifleLargeBP": {
  "name": "Rifle Ammo (large)",
  "icon": "icon_ammo_rifle.png",
  "cat": "ammo",
  "stats": [],
  "name_ja": "\u30e9\u30a4\u30d5\u30eb\u306e\u5f3e (\u5927)"
 },
 "AmmoShotgunBP": {
  "name": "Shotgun Ammo",
  "icon": "icon_ammo_shotgun.png",
  "cat": "ammo",
  "stats": [],
  "name_ja": "\u30b7\u30e7\u30c3\u30c8\u30ac\u30f3\u306e\u5f3e"
 },
 "AmmoShotgunLargeBP": {
  "name": "Shotgun Ammo (large)",
  "icon": "icon_ammo_shotgun.png",
  "cat": "ammo",
  "stats": [],
  "name_ja": "\u30b7\u30e7\u30c3\u30c8\u30ac\u30f3\u306e\u5f3e (\u5927)"
 },
 "AntibioticsBP": {
  "name": "Antibiotics",
  "icon": "icon_antibiotics.png",
  "cat": "medical",
  "stats": [],
  "name_ja": "\u6297\u751f\u7269\u8cea",
  "effect": "Low healing",
  "effect_ja": "\u56de\u5fa9\u91cf\uff1a\u4f4e"
 },
 "AntibioticsLargeBP": {
  "name": "Antibiotics (large)",
  "icon": "icon_antibiotics_lage.png",
  "cat": "medical",
  "stats": [],
  "name_ja": "\u6297\u751f\u7269\u8cea (\u5927)",
  "effect": "High healing",
  "effect_ja": "\u56de\u5fa9\u91cf\uff1a\u9ad8"
 },
 "BandagesBP": {
  "name": "Bandages",
  "icon": "icon_bandages.png",
  "cat": "medical",
  "stats": [],
  "name_ja": "\u5305\u5e2f",
  "effect": "Low healing",
  "effect_ja": "\u56de\u5fa9\u91cf\uff1a\u4f4e"
 },
 "BandagesLargeBP": {
  "name": "Bandages (large)",
  "icon": "icon_bandages_large.png",
  "cat": "medical",
  "stats": [],
  "name_ja": "\u5305\u5e2f (\u5927)",
  "effect": "High healing",
  "effect_ja": "\u56de\u5fa9\u91cf\uff1a\u9ad8"
 },
 "BeansBP": {
  "name": "Beans",
  "icon": "icon_beans.png",
  "cat": "food",
  "stats": [],
  "name_ja": "\u8c46\u306e\u7f36\u8a70",
  "effect": "Restores moderate hunger and puts a spring back in your step",
  "effect_ja": "\u7a7a\u8179\u3092\u4e2d\u7a0b\u5ea6\u56de\u5fa9\u3057\u3001\u811a\u306b\u5143\u6c17\u3092\u53d6\u308a\u623b\u3059"
 },
 "BiscuitBP": {
  "name": "Biscuit",
  "icon": "icon_biscuit.png",
  "cat": "food",
  "stats": [],
  "name_ja": "\u30d3\u30b9\u30b1\u30c3\u30c8",
  "effect": "Restores moderate hunger and puts a spring back in your step",
  "effect_ja": "\u7a7a\u8179\u3092\u4e2d\u7a0b\u5ea6\u56de\u5fa9\u3057\u3001\u811a\u306b\u5143\u6c17\u3092\u53d6\u308a\u623b\u3059"
 },
 "Boots01BP": {
  "name": "Exmoor Boots",
  "icon": "icon_boots_1.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "Very High"
   ]
  ],
  "name_ja": "\u30a8\u30af\u30b9\u30e0\u30fc\u30a2\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots02BP": {
  "name": "Cheviot Boots",
  "icon": "icon_boots_2.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "Very Low"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Stamina Bonus",
    "Very Low"
   ]
  ],
  "name_ja": "\u30c1\u30a7\u30d3\u30aa\u30c3\u30c8\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots03BP": {
  "name": "Pennine Boots",
  "icon": "icon_boots_3.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "Very Low"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Stamina Bonus",
    "Very Low"
   ]
  ],
  "name_ja": "\u30da\u30ca\u30a4\u30f3\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots04BP": {
  "name": "Dartmoor Boots",
  "icon": "icon_boots_4.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "Low"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Stamina Bonus",
    "Low"
   ]
  ],
  "name_ja": "\u30c0\u30fc\u30c8\u30e0\u30fc\u30a2\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots05BP": {
  "name": "Glencoe Boots",
  "icon": "icon_boots_5.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "Low"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Stamina Bonus",
    "Low"
   ]
  ],
  "name_ja": "\u30b0\u30ec\u30f3\u30b3\u30fc\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots06BP": {
  "name": "Tryfan Boots",
  "icon": "icon_boots_6.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "Moderate"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Stamina Bonus",
    "Moderate"
   ]
  ],
  "name_ja": "\u30c8\u30ea\u30d5\u30a1\u30f3\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots07BP": {
  "name": "Scafell Boots",
  "icon": "icon_boots_7.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "Moderate"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Stamina Bonus",
    "Moderate"
   ]
  ],
  "name_ja": "\u30b9\u30b3\u30fc\u30d5\u30a7\u30eb\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots08BP": {
  "name": "Nevis Boots",
  "icon": "icon_boots_8.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "High"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Stamina Bonus",
    "High"
   ]
  ],
  "name_ja": "\u30cd\u30d3\u30b9\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots09BP": {
  "name": "Dovedale Boots",
  "icon": "icon_boots_9.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "High"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Stamina Bonus",
    "High"
   ]
  ],
  "name_ja": "\u30c0\u30f4\u30c7\u30a4\u30eb\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots10BP": {
  "name": "Torridon Boots",
  "icon": "icon_boots_10.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "Very High"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Stamina Bonus",
    "Very High"
   ]
  ],
  "name_ja": "\u30c8\u30ea\u30c9\u30f3\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots11BP": {
  "name": "Cairngorm Boots",
  "icon": "icon_boots_11.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "Very High"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Stamina Bonus",
    "Very High"
   ]
  ],
  "name_ja": "\u30b1\u30a2\u30f3\u30b4\u30fc\u30e0\u30fb\u30d6\u30fc\u30c4"
 },
 "Boots12BP": {
  "name": "Pentland Boots",
  "icon": "icon_boots_12.png",
  "cat": "boots",
  "stats": [
   [
    "Durability",
    "Very High"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Stamina Bonus",
    "Very High"
   ]
  ],
  "name_ja": "\u30da\u30f3\u30c8\u30e9\u30f3\u30c9\u30fb\u30d6\u30fc\u30c4"
 },
 "CornedBeefBP": {
  "name": "Corned Beef",
  "icon": "icon_cornedbeef.png",
  "cat": "food",
  "stats": [],
  "name_ja": "\u30b3\u30f3\u30d3\u30fc\u30d5",
  "effect": "Restores moderate hunger and puts a spring back in your step",
  "effect_ja": "\u7a7a\u8179\u3092\u4e2d\u7a0b\u5ea6\u56de\u5fa9\u3057\u3001\u811a\u306b\u5143\u6c17\u3092\u53d6\u308a\u623b\u3059"
 },
 "DressingBP": {
  "name": "Dressing",
  "icon": "icon_dressing.png",
  "cat": "medical",
  "stats": [],
  "name_ja": "\u533b\u7642\u7528\u30d1\u30c3\u30c9",
  "effect": "Low healing",
  "effect_ja": "\u56de\u5fa9\u91cf\uff1a\u4f4e"
 },
 "DressingLargeBP": {
  "name": "Dressing (large)",
  "icon": "icon_dressing_large.png",
  "cat": "medical",
  "stats": [],
  "name_ja": "\u533b\u7642\u7528\u30d1\u30c3\u30c9 (\u5927)",
  "effect": "High healing",
  "effect_ja": "\u56de\u5fa9\u91cf\uff1a\u9ad8"
 },
 "EnergyDrinkBP": {
  "name": "Energy Drink",
  "icon": "icon_energydrink.png",
  "cat": "drink",
  "stats": [],
  "name_ja": "\u30a8\u30ca\u30b8\u30fc\u30c9\u30ea\u30f3\u30af",
  "effect": "Quenches moderate thirst and restores some stamina",
  "effect_ja": "\u6e07\u304d\u3092\u4e2d\u7a0b\u5ea6\u7652\u3057\u3001\u30b9\u30bf\u30df\u30ca\u3082\u56de\u5fa9"
 },
 "EnergyDrinkLargeBP": {
  "name": "Energy Drink (large)",
  "icon": "icon_energydrink_large.png",
  "cat": "drink",
  "stats": [],
  "name_ja": "\u30a8\u30ca\u30b8\u30fc\u30c9\u30ea\u30f3\u30af (\u5927)",
  "effect": "Quenches high thirst and restores some stamina",
  "effect_ja": "\u6e07\u304d\u3092\u5927\u304d\u304f\u7652\u3057\u3001\u30b9\u30bf\u30df\u30ca\u3082\u56de\u5fa9"
 },
 "JacketOneBP": {
  "name": "Mallard Clothes",
  "icon": "icon_jacket_1.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "Very High"
   ]
  ],
  "name_ja": "\u30de\u30e9\u30fc\u30c9\u306e\u670d"
 },
 "JacketTwoBP": {
  "name": "Mandarin Clothes",
  "icon": "icon_jacket_2.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "Very Low"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Armour",
    "Low"
   ]
  ],
  "name_ja": "\u30de\u30f3\u30c0\u30ea\u30f3\u306e\u670d"
 },
 "JacketThreeBP": {
  "name": "Gadwall Clothes",
  "icon": "icon_jacket_3.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "Very Low"
   ],
   [
    "Rain Resistance",
    "Low"
   ]
  ],
  "name_ja": "\u30ac\u30c9\u30a6\u30a9\u30fc\u30eb\u306e\u670d"
 },
 "JacketFourBP": {
  "name": "Shelduck Clothes",
  "icon": "icon_jacket_4.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "Low"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Armour",
    "Low"
   ]
  ],
  "name_ja": "\u30b7\u30a7\u30eb\u30c0\u30c3\u30af\u306e\u670d"
 },
 "JacketFiveBP": {
  "name": "Pintail Clothes",
  "icon": "icon_jacket_5.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "Low"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Armour",
    "Moderate"
   ]
  ],
  "name_ja": "\u30d4\u30f3\u30c6\u30fc\u30eb\u306e\u670d"
 },
 "JacketSixBP": {
  "name": "Shoveler Clothes",
  "icon": "icon_jacket_6.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "Moderate"
   ],
   [
    "Rain Resistance",
    "Moderate"
   ],
   [
    "Armour",
    "Low"
   ]
  ],
  "name_ja": "\u30b7\u30e7\u30d9\u30e9\u30fc\u306e\u670d"
 },
 "JacketSevenBP": {
  "name": "Pochard Clothes",
  "icon": "icon_jacket_7.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "Moderate"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Armour",
    "Moderate"
   ]
  ],
  "name_ja": "\u30dd\u30c1\u30e3\u30fc\u30c9\u306e\u670d"
 },
 "JacketEightBP": {
  "name": "Tufted Clothes",
  "icon": "icon_jacket_8.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "High"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Armour",
    "Low"
   ]
  ],
  "name_ja": "\u30bf\u30d5\u30c6\u30c3\u30c9\u306e\u670d"
 },
 "JacketNineBP": {
  "name": "Teal Clothes",
  "icon": "icon_jacket_9.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "High"
   ],
   [
    "Rain Resistance",
    "Moderate"
   ],
   [
    "Armour",
    "Moderate"
   ]
  ],
  "name_ja": "\u30c6\u30a3\u30fc\u30eb\u306e\u670d"
 },
 "JacketTenBP": {
  "name": "Eider Clothes",
  "icon": "icon_jacket_10.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "Very High"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Armour",
    "Low"
   ]
  ],
  "name_ja": "\u30a2\u30a4\u30c0\u30fc\u306e\u670d"
 },
 "JacketElevenBP": {
  "name": "Merganser Clothes",
  "icon": "icon_jacket_11.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "Very High"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Armour",
    "High"
   ]
  ],
  "name_ja": "\u30de\u30fc\u30ac\u30f3\u30b5\u30fc\u306e\u670d"
 },
 "JacketTwelveBP": {
  "name": "Scoter Clothes",
  "icon": "icon_jacket_12.png",
  "cat": "jacket",
  "stats": [
   [
    "Durability",
    "Very High"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Armour",
    "High"
   ]
  ],
  "name_ja": "\u30b9\u30b3\u30fc\u30bf\u30fc\u306e\u670d"
 },
 "MintCakeBP": {
  "name": "Mint Cake",
  "icon": "icon_mintcake.png",
  "cat": "food",
  "stats": [],
  "name_ja": "\u30df\u30f3\u30c8\u30b1\u30fc\u30ad",
  "effect": "Restores moderate hunger and puts a spring back in your step",
  "effect_ja": "\u7a7a\u8179\u3092\u4e2d\u7a0b\u5ea6\u56de\u5fa9\u3057\u3001\u811a\u306b\u5143\u6c17\u3092\u53d6\u308a\u623b\u3059"
 },
 "NoodlesBP": {
  "name": "Noodles",
  "icon": "icon_noodles.png",
  "cat": "food",
  "stats": [],
  "name_ja": "\u30cc\u30fc\u30c9\u30eb",
  "effect": "Restores moderate hunger and puts a spring back in your step",
  "effect_ja": "\u7a7a\u8179\u3092\u4e2d\u7a0b\u5ea6\u56de\u5fa9\u3057\u3001\u811a\u306b\u5143\u6c17\u3092\u53d6\u308a\u623b\u3059"
 },
 "Perk1StaminaRecovertBP": {
  "name": "Secret Filter Journal",
  "icon": "icon_journal_staminarecovery.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u79d8\u5bc6\u306e\u30d5\u30a3\u30eb\u30bf\u30fc\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Stamina returns faster while you carry this",
  "effect_ja": "\u30b9\u30bf\u30df\u30ca\u306e\u56de\u5fa9\u304c\u901f\u304f\u306a\u308b"
 },
 "Perk2PHRecoveryBP": {
  "name": "pH Primer Journal",
  "icon": "icon_journal_phrecovery.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "pH\u5165\u9580\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Your pH meter recovers more quickly after the rain",
  "effect_ja": "\u96e8\u4e0a\u304c\u308a\u306epH\u30e1\u30fc\u30bf\u30fc\u306e\u56de\u5fa9\u304c\u901f\u304f\u306a\u308b"
 },
 "Perk3ThirstBP": {
  "name": "Last Drop Journal",
  "icon": "icon_journals_thirst.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u6700\u5f8c\u306e\u4e00\u6ef4\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Thirst creeps up more slowly",
  "effect_ja": "\u6e07\u304d\u306e\u9032\u884c\u304c\u9045\u304f\u306a\u308b"
 },
 "Perk4HungerBP": {
  "name": "Slow Burn Journal",
  "icon": "icon_journal_hunger.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u30b9\u30ed\u30fc\u30d0\u30fc\u30f3\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Hunger gnaws more slowly",
  "effect_ja": "\u7a7a\u8179\u306e\u9032\u884c\u304c\u9045\u304f\u306a\u308b"
 },
 "Perk5BatteryBP": {
  "name": "Power Saver Journal",
  "icon": "icon_journal_battery.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u7701\u96fb\u529b\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Torch and map drain the battery more slowly",
  "effect_ja": "\u30e9\u30a4\u30c8\u3068\u30de\u30c3\u30d7\u306e\u30d0\u30c3\u30c6\u30ea\u30fc\u6d88\u8cbb\u304c\u6e1b\u308b"
 },
 "Perk6UmbrellaFallBP": {
  "name": "Poppin's Journal",
  "icon": "icon_journal_umbrella_fall.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u30dd\u30d4\u30f3\u30ba\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Fall gently from any height \u2014 umbrella raised, of course",
  "effect_ja": "\u3069\u3093\u306a\u9ad8\u3055\u304b\u3089\u3082\u3001\u3075\u308f\u308a\u3068\u964d\u4e0b \u2015 \u3082\u3061\u308d\u3093\u5098\u306f\u5dee\u3057\u3066"
 },
 "Perk7GunDamageBP": {
  "name": "Soldiers's Journal",
  "icon": "icon_journal_gundamage.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u5175\u58eb\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Firearms hit harder",
  "effect_ja": "\u9283\u5668\u306e\u653b\u6483\u529b\u304c\u4e0a\u304c\u308b"
 },
 "Perk8CrossbowDamageBP": {
  "name": "Fletcher's Journal",
  "icon": "icon_journal_crossbowdamage.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u77e2\u8077\u4eba\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Crossbow bolts hit harder",
  "effect_ja": "\u30af\u30ed\u30b9\u30dc\u30a6\u306e\u653b\u6483\u529b\u304c\u4e0a\u304c\u308b"
 },
 "Perk9MeleeDamageBP": {
  "name": "Brolly Journal",
  "icon": "icon_journal_meleedamage.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u96e8\u5098\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Umbrella swings hit harder",
  "effect_ja": "\u5098\u306e\u653b\u6483\u529b\u304c\u4e0a\u304c\u308b"
 },
 "Perk10StaminaBoostBP": {
  "name": "Run Smart Journal",
  "icon": "icon_journal_staminaboost.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u8ce2\u304f\u8d70\u308b\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "A deeper stamina reserve",
  "effect_ja": "\u30b9\u30bf\u30df\u30ca\u306e\u6d88\u8cbb\u304c\u6e1b\u308b"
 },
 "Perk12ArmourBP": {
  "name": "Sashiko Journal",
  "icon": "icon_journals_armour.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u523a\u3057\u5b50\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Stitch-reinforced clothing takes more punishment",
  "effect_ja": "\u88dc\u5f37\u3055\u308c\u305f\u8863\u670d\u304c\u3088\u308a\u9577\u6301\u3061\u3059\u308b"
 },
 "Perk13RainResistanceBP": {
  "name": "A Rain Walker's Journal",
  "icon": "icon_journals_rainresistance.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u30ec\u30a4\u30f3\u30a6\u30a9\u30fc\u30ab\u30fc\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Everything you wear soaks through more slowly",
  "effect_ja": "\u8eab\u306b\u3064\u3051\u305f\u88c5\u5099\u304c\u6fe1\u308c\u306b\u304f\u304f\u306a\u308b"
 },
 "Perk14SprintBP": {
  "name": "Dead Heels Journal",
  "icon": "icon_journal_sprint.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u30c7\u30c3\u30c9\u30d2\u30fc\u30eb\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Sprint faster than the dead can shamble",
  "effect_ja": "\u6b7b\u8005\u306e\u8db3\u53d6\u308a\u3088\u308a\u901f\u304f\u30c0\u30c3\u30b7\u30e5\u3067\u304d\u308b"
 },
 "Perk15RidingBP": {
  "name": "Stubborn Beasts Journal",
  "icon": "icon_journal_riding.png",
  "cat": "journal",
  "stats": [],
  "name_ja": "\u9811\u56fa\u306a\u7363\u306e\u30b8\u30e3\u30fc\u30ca\u30eb",
  "effect": "Persuade the zone's stubborn beasts to carry you",
  "effect_ja": "\u30be\u30fc\u30f3\u306e\u9811\u56fa\u306a\u7363\u305f\u3061\u306b\u4e57\u305b\u3066\u3082\u3089\u3048\u308b"
 },
 "Umbrella1BP": {
  "name": "Oxford Umbrella",
  "icon": "icon_umbrella1.png",
  "cat": "umbrella",
  "stats": [
   [
    "Vs Survivors",
    "Very Low"
   ],
   [
    "Vs Undead",
    "Low"
   ],
   [
    "Durability",
    "Very Low"
   ]
  ],
  "name_ja": "\u30aa\u30c3\u30af\u30b9\u30d5\u30a9\u30fc\u30c9\u306e\u5098"
 },
 "Umbrella2BP": {
  "name": "Regent Umbrella",
  "icon": "icon_umbrella2.png",
  "cat": "umbrella",
  "stats": [
   [
    "Vs Survivors",
    "Very Low"
   ],
   [
    "Vs Undead",
    "Low"
   ],
   [
    "Durability",
    "Low"
   ]
  ],
  "name_ja": "\u30ea\u30fc\u30b8\u30a7\u30f3\u30c8\u306e\u5098"
 },
 "Umbrella3BP": {
  "name": "Strand Umbrella",
  "icon": "icon_umbrella3.png",
  "cat": "umbrella",
  "stats": [
   [
    "Vs Survivors",
    "Low"
   ],
   [
    "Vs Undead",
    "Low"
   ],
   [
    "Durability",
    "Moderate"
   ]
  ],
  "name_ja": "\u30b9\u30c8\u30e9\u30f3\u30c9\u306e\u5098"
 },
 "Umbrella4BP": {
  "name": "Greyfriar Umbrella",
  "icon": "icon_umbrella4.png",
  "cat": "umbrella",
  "stats": [
   [
    "Vs Survivors",
    "Moderate"
   ],
   [
    "Vs Undead",
    "Moderate"
   ],
   [
    "Durability",
    "High"
   ]
  ],
  "name_ja": "\u30b0\u30ec\u30fc\u30d5\u30e9\u30a4\u30a2\u306e\u5098"
 },
 "Umbrella5BP": {
  "name": "Kensington Umbrella",
  "icon": "icon_umbrella5.png",
  "cat": "umbrella",
  "stats": [
   [
    "Vs Survivors",
    "High"
   ],
   [
    "Vs Undead",
    "High"
   ],
   [
    "Durability",
    "Very High"
   ]
  ],
  "name_ja": "\u30b1\u30f3\u30b8\u30f3\u30c8\u30f3\u306e\u5098"
 },
 "Umbrella6BP": {
  "name": "Trafalgar Umbrella",
  "icon": "icon_umbrella6.png",
  "cat": "umbrella",
  "stats": [
   [
    "Vs Survivors",
    "Very High"
   ],
   [
    "Vs Undead",
    "High"
   ],
   [
    "Durability",
    "Very High"
   ]
  ],
  "name_ja": "\u30c8\u30e9\u30d5\u30a1\u30eb\u30ac\u30fc\u306e\u5098"
 },
 "TunaBP": {
  "name": "Tuna",
  "icon": "icon_tuna.png",
  "cat": "food",
  "stats": [],
  "name_ja": "\u30c4\u30ca",
  "effect": "Restores moderate hunger and puts a spring back in your step",
  "effect_ja": "\u7a7a\u8179\u3092\u4e2d\u7a0b\u5ea6\u56de\u5fa9\u3057\u3001\u811a\u306b\u5143\u6c17\u3092\u53d6\u308a\u623b\u3059"
 },
 "SoupBP": {
  "name": "Soup",
  "icon": "icon_soup.png",
  "cat": "food",
  "stats": [],
  "name_ja": "\u30b9\u30fc\u30d7",
  "effect": "Restores moderate hunger and puts a spring back in your step",
  "effect_ja": "\u7a7a\u8179\u3092\u4e2d\u7a0b\u5ea6\u56de\u5fa9\u3057\u3001\u811a\u306b\u5143\u6c17\u3092\u53d6\u308a\u623b\u3059"
 },
 "RicePuddingBP": {
  "name": "Rice Pudding",
  "icon": "icon_ricepudding.png",
  "cat": "food",
  "stats": [],
  "name_ja": "\u30e9\u30a4\u30b9\u30d7\u30c7\u30a3\u30f3\u30b0",
  "effect": "Restores moderate hunger and puts a spring back in your step",
  "effect_ja": "\u7a7a\u8179\u3092\u4e2d\u7a0b\u5ea6\u56de\u5fa9\u3057\u3001\u811a\u306b\u5143\u6c17\u3092\u53d6\u308a\u623b\u3059"
 },
 "SnackbarBP": {
  "name": "Energy Bar",
  "icon": "icon_snackbar.png",
  "cat": "food",
  "stats": [],
  "name_ja": "\u30a8\u30ca\u30b8\u30fc\u30d0\u30fc",
  "effect": "Restores moderate hunger and puts a spring back in your step",
  "effect_ja": "\u7a7a\u8179\u3092\u4e2d\u7a0b\u5ea6\u56de\u5fa9\u3057\u3001\u811a\u306b\u5143\u6c17\u3092\u53d6\u308a\u623b\u3059"
 },
 "SatelliteDishPartBP": {
  "name": "Satellite Dish Part",
  "icon": "icon_satellitedishpart.png",
  "cat": "mission",
  "stats": [],
  "name_ja": "\u885b\u661f\u30a2\u30f3\u30c6\u30ca\u306e\u30d1\u30fc\u30c4"
 },
 "RadioTowerPartBP": {
  "name": "Radio Tower Part",
  "icon": "icon_radiotowerpart.png",
  "cat": "mission",
  "stats": [],
  "name_ja": "\u96fb\u6ce2\u5854\u306e\u30d1\u30fc\u30c4"
 },
 "PoliceKeycardBP": {
  "name": "Police Station Keycard",
  "icon": "icon_policekeycard.png",
  "cat": "mission",
  "stats": [],
  "name_ja": "\u8b66\u5bdf\u7f72\u306e\u30ad\u30fc\u30ab\u30fc\u30c9"
 },
 "MilitaryIDBP": {
  "name": "Military ID Card",
  "icon": "icon_militaryidcard.png",
  "cat": "mission",
  "stats": [],
  "name_ja": "\u8ecd\u306eID\u30ab\u30fc\u30c9"
 },
 "BunkerKeycardBP": {
  "name": "Bunker Door Keycard",
  "icon": "icon_bunkerkeycard.png",
  "cat": "mission",
  "stats": [],
  "name_ja": "\u30d0\u30f3\u30ab\u30fc\u30c9\u30a2\u306e\u30ad\u30fc\u30ab\u30fc\u30c9"
 },
 "WaterBottleBP": {
  "name": "Water",
  "icon": "icon_water.png",
  "cat": "drink",
  "stats": [],
  "name_ja": "\u6c34",
  "effect": "Quenches low thirst and restores some stamina",
  "effect_ja": "\u6e07\u304d\u3092\u5c11\u3057\u7652\u3057\u3001\u30b9\u30bf\u30df\u30ca\u3082\u56de\u5fa9"
 },
 "WaterBottleLargeBP": {
  "name": "Water (large)",
  "icon": "icon_water_large.png",
  "cat": "drink",
  "stats": [],
  "name_ja": "\u6c34 (\u5927)",
  "effect": "Quenches high thirst and restores some stamina",
  "effect_ja": "\u6e07\u304d\u3092\u5927\u304d\u304f\u7652\u3057\u3001\u30b9\u30bf\u30df\u30ca\u3082\u56de\u5fa9"
 },
 "BackpackOneBP": {
  "name": "Hedgehog Backpack",
  "icon": "icon_backpack_one.png",
  "cat": "backpack",
  "stats": [
   [
    "Capacity",
    "Very Low"
   ]
  ],
  "name_ja": "\u30d8\u30c3\u30b8\u30db\u30c3\u30b0\u30fb\u30d0\u30c3\u30af\u30d1\u30c3\u30af"
 },
 "BackpackOneAltBP": {
  "name": "Fox Backpack",
  "icon": "icon_backpack_one_alt.png",
  "cat": "backpack",
  "stats": [
   [
    "Capacity",
    "Very Low"
   ]
  ],
  "name_ja": "\u30d5\u30a9\u30c3\u30af\u30b9\u30fb\u30d0\u30c3\u30af\u30d1\u30c3\u30af"
 },
 "BackpackTwoBP": {
  "name": "Otter Backpack",
  "icon": "icon_backpack_two.png",
  "cat": "backpack",
  "stats": [
   [
    "Capacity",
    "Low"
   ]
  ],
  "name_ja": "\u30aa\u30c3\u30bf\u30fc\u30fb\u30d0\u30c3\u30af\u30d1\u30c3\u30af"
 },
 "BackpackTwoAltBP": {
  "name": "Badger Backpack",
  "icon": "icon_backpack_two_alt.png",
  "cat": "backpack",
  "stats": [
   [
    "Capacity",
    "Low"
   ]
  ],
  "name_ja": "\u30d0\u30b8\u30e3\u30fc\u30fb\u30d0\u30c3\u30af\u30d1\u30c3\u30af"
 },
 "BackpackThreeBP": {
  "name": "Hare Backpack",
  "icon": "icon_backpack_three.png",
  "cat": "backpack",
  "stats": [
   [
    "Capacity",
    "Moderate"
   ]
  ],
  "name_ja": "\u30d8\u30a2\u30fb\u30d0\u30c3\u30af\u30d1\u30c3\u30af"
 },
 "BackpackThreeAltBP": {
  "name": "Stoat Backpack",
  "icon": "icon_backpack_three_alt.png",
  "cat": "backpack",
  "stats": [
   [
    "Capacity",
    "Moderate"
   ]
  ],
  "name_ja": "\u30b9\u30c8\u30fc\u30c8\u30fb\u30d0\u30c3\u30af\u30d1\u30c3\u30af"
 },
 "BackpackFourBP": {
  "name": "Deer Backpack",
  "icon": "icon_backpack_four.png",
  "cat": "backpack",
  "stats": [
   [
    "Capacity",
    "High"
   ]
  ],
  "name_ja": "\u30c7\u30a3\u30a2\u30fb\u30d0\u30c3\u30af\u30d1\u30c3\u30af"
 },
 "BackpackFourAltBP": {
  "name": "Wildcat Backpack",
  "icon": "icon_backpack_four_alt.png",
  "cat": "backpack",
  "stats": [
   [
    "Capacity",
    "High"
   ]
  ],
  "name_ja": "\u30ef\u30a4\u30eb\u30c9\u30ad\u30e3\u30c3\u30c8\u30fb\u30d0\u30c3\u30af\u30d1\u30c3\u30af"
 },
 "BackpackFiveBP": {
  "name": "Boar Backpack",
  "icon": "icon_backpack_five.png",
  "cat": "backpack",
  "stats": [
   [
    "Capacity",
    "Very High"
   ]
  ],
  "name_ja": "\u30dc\u30a2\u30fb\u30d0\u30c3\u30af\u30d1\u30c3\u30af"
 },
 "BackpackFiveAltBP": {
  "name": "Stag Backpack",
  "icon": "icon_backpack_five_alt.png",
  "cat": "backpack",
  "stats": [
   [
    "Capacity",
    "Very High"
   ]
  ],
  "name_ja": "\u30b9\u30bf\u30c3\u30b0\u30fb\u30d0\u30c3\u30af\u30d1\u30c3\u30af"
 },
 "maskoneBP": {
  "name": "Bug Mask",
  "icon": "icon_basic_mask.png",
  "cat": "mask",
  "stats": [
   [
    "Durability",
    "Very High"
   ]
  ],
  "name_ja": "\u30d0\u30b0\u30fb\u30de\u30b9\u30af"
 },
 "maskoneAltBP": {
  "name": "Gnat Mask",
  "icon": "icon_mask_one_alt.png",
  "cat": "mask",
  "stats": [
   [
    "Durability",
    "Very Low"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Armour",
    "Low"
   ]
  ],
  "name_ja": "\u30d6\u30e6\u30fb\u30de\u30b9\u30af"
 },
 "masktwoBP": {
  "name": "Ant Mask",
  "icon": "icon_mask_two.png",
  "cat": "mask",
  "stats": [
   [
    "Durability",
    "Very Low"
   ],
   [
    "Rain Resistance",
    "Moderate"
   ]
  ],
  "name_ja": "\u30a2\u30f3\u30c8\u30fb\u30de\u30b9\u30af"
 },
 "masktwoAltBP": {
  "name": "Moth Mask",
  "icon": "icon_mask_two_alt.png",
  "cat": "mask",
  "stats": [
   [
    "Durability",
    "Low"
   ],
   [
    "Rain Resistance",
    "Moderate"
   ],
   [
    "Armour",
    "Low"
   ]
  ],
  "name_ja": "\u30e2\u30b9\u30fb\u30de\u30b9\u30af"
 },
 "maskthreeBP": {
  "name": "Cricket Mask",
  "icon": "icon_mask_three.png",
  "cat": "mask",
  "stats": [
   [
    "Durability",
    "Low"
   ],
   [
    "Rain Resistance",
    "Low"
   ],
   [
    "Armour",
    "High"
   ]
  ],
  "name_ja": "\u30af\u30ea\u30b1\u30c3\u30c8\u30fb\u30de\u30b9\u30af"
 },
 "maskthreeAltBP": {
  "name": "Beetle Mask",
  "icon": "icon_mask_three_alt.png",
  "cat": "mask",
  "stats": [
   [
    "Durability",
    "Moderate"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Armour",
    "Low"
   ]
  ],
  "name_ja": "\u30d3\u30fc\u30c8\u30eb\u30fb\u30de\u30b9\u30af"
 },
 "maskfourBP": {
  "name": "Wasp Mask",
  "icon": "icon_mask_four.png",
  "cat": "mask",
  "stats": [
   [
    "Durability",
    "High"
   ],
   [
    "Rain Resistance",
    "Moderate"
   ],
   [
    "Armour",
    "High"
   ]
  ],
  "name_ja": "\u30ef\u30b9\u30d7\u30fb\u30de\u30b9\u30af"
 },
 "maskfourAltBP": {
  "name": "Hornet Mask",
  "icon": "icon_mask_four_alt.png",
  "cat": "mask",
  "stats": [
   [
    "Durability",
    "High"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Armour",
    "Low"
   ]
  ],
  "name_ja": "\u30db\u30fc\u30cd\u30c3\u30c8\u30fb\u30de\u30b9\u30af"
 },
 "maskfiveBP": {
  "name": "Firefly Mask",
  "icon": "icon_mask_five.png",
  "cat": "mask",
  "stats": [
   [
    "Durability",
    "Very High"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Armour",
    "High"
   ]
  ],
  "name_ja": "\u30d5\u30a1\u30a4\u30a2\u30d5\u30e9\u30a4\u30fb\u30de\u30b9\u30af"
 },
 "maskfiveAltBP": {
  "name": "Dragonfly Mask",
  "icon": "icon_mask_five_alt.png",
  "cat": "mask",
  "stats": [
   [
    "Durability",
    "Very High"
   ],
   [
    "Rain Resistance",
    "High"
   ],
   [
    "Armour",
    "High"
   ]
  ],
  "name_ja": "\u30c9\u30e9\u30b4\u30f3\u30d5\u30e9\u30a4\u30fb\u30de\u30b9\u30af"
 }
};
const RSZ_ORDER = {
 "handgun": [
  "ColtBP",
  "ColtAltBP",
  "GlockBP",
  "GlockAltBP",
  "DeagleBP",
  "DeagleAltBP"
 ],
 "rifle": [
  "RifleOneBP",
  "RifleOneAltBP",
  "RifleTwoBP",
  "RifleTwoAltBP",
  "RifleThreeBP",
  "RifleThreeAltBP"
 ],
 "shotgun": [
  "ShotgunOneBP",
  "ShotgunOneAltBP",
  "ShotgunTwoBP",
  "ShotgunTwoAltBP",
  "ShotgunThreeBP",
  "ShotgunThreeAltBP"
 ],
 "crossbow": [
  "CrossbowOneBP",
  "CrossbowOneAltBP",
  "CrossbowTwoBP",
  "CrossbowTwoAltBP",
  "CrossbowThreeBP",
  "CrossbowThreeAltBP"
 ],
 "umbrella": [
  "Umbrella1BP",
  "Umbrella2BP",
  "Umbrella3BP",
  "Umbrella4BP",
  "Umbrella5BP",
  "Umbrella6BP"
 ],
 "ammo": [
  "AmmoHandgunBP",
  "AmmoHandgunLargeBP",
  "AmmoRifleBP",
  "AmmoRifleLargeBP",
  "AmmoShotgunBP",
  "AmmoShotgunLargeBP",
  "AmmoCrossbowBP",
  "AmmoCrossbowLargeBP"
 ],
 "mask": [
  "maskoneBP",
  "maskoneAltBP",
  "masktwoBP",
  "masktwoAltBP",
  "maskthreeBP",
  "maskthreeAltBP",
  "maskfourBP",
  "maskfourAltBP",
  "maskfiveBP",
  "maskfiveAltBP"
 ],
 "jacket": [
  "JacketOneBP",
  "JacketTwoBP",
  "JacketThreeBP",
  "JacketFourBP",
  "JacketFiveBP",
  "JacketSixBP",
  "JacketSevenBP",
  "JacketEightBP",
  "JacketNineBP",
  "JacketTenBP",
  "JacketElevenBP",
  "JacketTwelveBP"
 ],
 "boots": [
  "Boots01BP",
  "Boots02BP",
  "Boots03BP",
  "Boots04BP",
  "Boots05BP",
  "Boots06BP",
  "Boots07BP",
  "Boots08BP",
  "Boots09BP",
  "Boots10BP",
  "Boots11BP",
  "Boots12BP"
 ],
 "backpack": [
  "BackpackOneBP",
  "BackpackOneAltBP",
  "BackpackTwoBP",
  "BackpackTwoAltBP",
  "BackpackThreeBP",
  "BackpackThreeAltBP",
  "BackpackFourBP",
  "BackpackFourAltBP",
  "BackpackFiveBP",
  "BackpackFiveAltBP"
 ],
 "food": [
  "BeansBP",
  "SoupBP",
  "CornedBeefBP",
  "TunaBP",
  "BiscuitBP",
  "RicePuddingBP",
  "SnackbarBP",
  "MintCakeBP",
  "NoodlesBP"
 ],
 "drink": [
  "WaterBottleBP",
  "WaterBottleLargeBP",
  "EnergyDrinkBP",
  "EnergyDrinkLargeBP"
 ],
 "medical": [
  "BandagesBP",
  "BandagesLargeBP",
  "DressingBP",
  "DressingLargeBP",
  "AntibioticsBP",
  "AntibioticsLargeBP"
 ],
 "journal": [
  "Perk1StaminaRecovertBP",
  "Perk2PHRecoveryBP",
  "Perk3ThirstBP",
  "Perk4HungerBP",
  "Perk5BatteryBP",
  "Perk6UmbrellaFallBP",
  "Perk7GunDamageBP",
  "Perk8CrossbowDamageBP",
  "Perk9MeleeDamageBP",
  "Perk10StaminaBoostBP",
  "Perk12ArmourBP",
  "Perk13RainResistanceBP",
  "Perk14SprintBP",
  "Perk15RidingBP"
 ],
 "mission": [
  "PoliceKeycardBP",
  "MilitaryIDBP",
  "BunkerKeycardBP",
  "RadioTowerPartBP",
  "SatelliteDishPartBP"
 ]
};
