/* Rain Station Z — サバイバルハンドブック (Japanese edition)
   Page content only; layout helpers are passed in from manual.js.
   Terminology follows the game's official localisation (reference/Game.archive):
   item names, location names, photo-mode sliders, action verbs, the pH warning
   and the mission briefs are all the game's own strings (item names arrive via
   data.js name_ja, generated by tools/build_data.py from the archive).
   Prose is a translation of the English pages in js/manual.js — when editing
   copy there, mirror the change here. */

window.RSZ_JA_BUILD = function (H) {
  "use strict";
  const { photo, head, spec, gitem, jitem, gaz, RUN } = H;

  const P = [];

  /* 表紙 ------------------------------------------------------------------ */
  P.push({ no: null, cls: "cover", html: `
    <img class="logo" src="assets/art/game_logo_jp.png" alt="レインステーションZ">
    <div class="strip">サバイバルハンドブック</div>
    <div class="art">${photo("shots/shot_survivor_portrait.jpg", "楽観は標準装備に含まれません。")}</div>
    <div class="badges">
      <span class="badge">Steam</span>
      <span class="badge">PlayStation 5</span>
      <span class="badge rating"><span class="big">D</span><span>ずぶ濡れ指定</span></span>
      <span class="badge">Nintendo Switch</span>
    </div>` });

  /* 見返し — 警告 ---------------------------------------------------------- */
  P.push({ no: null, cls: "stained", html: `
    <div class="warnbox">
      <h3>&#9888; 安全に関する重要なお知らせ &#9888;</h3>
      <p class="body"><span class="lead">警告 ― 外出前にお読みください。</span>
      RAIN STATION Z を長時間プレイすると、心拍数の上昇、靴下の湿り、缶詰を
      溜め込みたくなる衝動、傘への強すぎるこだわりなどの症状が現れることが
      あります。ごく一部のプレイヤーは「誰かにつけられている」感覚を覚える
      ことがあります。それは気のせいではありません。</p>
      <p class="body"><span class="lead">降水に関するお知らせ。</span>本作の雨は
      飲料水ではありません。雨を舐めないでください。pHメーターがゼロを示して
      いる場合、あなたはすでに雨を舐めています。直ちに屋根の下へ。</p>
      <p class="body"><span class="lead">バッテリーに関する注意。</span>ライトは
      バッテリーを消耗します。マップもバッテリーを消耗します。勇気はもっとも
      速くバッテリーを消耗します。電池の交換は、必ず乾いた場所で。</p>
      <p class="body"><span class="lead">健康のために：</span>1時間ごとに15分の
      休憩を取りましょう。ゾンビの群れが玄関先に来ていても、です。群れは
      待ってくれます。彼らには、時間だけは山ほどあるのです。</p>
    </div>
    <p class="body typewriter" style="text-align:center">本書は再生紙に印刷されて
    います。ゾーンの中では、すべての紙が再生紙です。</p>
    ${RUN}` });

  /* p1 — 扉 ---------------------------------------------------------------- */
  P.push({ no: 1, cls: "stained", html: `
    <div style="text-align:center; margin-top:8%">
      <img src="assets/art/game_logo_jp.png" alt="レインステーションZ" style="width:80%">
      <p class="typewriter" style="margin-top:6%; letter-spacing:.3em; font-size:14px">
        公式サバイバルハンドブック</p>
      <p class="typewriter" style="margin-top:1%; font-size:11px; color:var(--ink-soft)">
        初版 ― 少々水濡れあり</p>
      <div style="margin:9% auto; width:55%; border-top:1.5px solid var(--ink); border-bottom:1.5px solid var(--ink); padding:.8em 0">
        <p class="body" style="text-align:center; margin:0">
          雨は、もうずっと降り続いています。<br>
          この本は、あなたが生き延びる手助けをします。<br>
          どうか濡らさないでください。</p>
      </div>
      <p class="typewriter" style="font-size:11px; color:var(--ink-soft)">
        WOBBLY TOOTH LIMITED</p>
    </div>
    <div class="fieldnote">3日目に郵便受けで見つけた。書いた奴は分かってる。
    余白に自分のメモを書き足しておいた ― 無視するなら自己責任で。
    濡れるな、死ぬな。 <b>― M.</b></div>
    ${RUN}` });

  /* p2 — 目次 --------------------------------------------------------------- */
  const TOC = [
    ["これまでのあらすじ", 3], ["サバイバーの基本", 4], ["サバイバーアクション", 5],
    ["雨", 6], ["武器庫", 8], ["装備", 14],
    ["食料と応急手当", 18], ["サバイバーのジャーナル", 20],
    ["ミッション", 22], ["ゾーン", 24], ["アンデッド", 26],
    ["共に生き延びる", 27], ["フォトモード", 28], ["フィールド機能", 29],
    ["フィールドノート", 30], ["クレジット", 31],
  ];
  P.push({ no: 2, html: `
    ${head("&#167;", "目次")}
    <div class="toc">${TOC.map(([t, pg]) =>
      `<div class="tocline" data-goto="${pg}"><span class="t">${t}</span><span class="dots"></span><span class="pg">${pg}</span></div>`).join("")}
    </div>
    <div class="fieldnote">6ページと7ページが命綱だ。二度読め。 <b>― M.</b></div>
    ${RUN}` });

  /* p3 — あらすじ ------------------------------------------------------------ */
  P.push({ no: 3, cls: "stained", html: `
    ${head("1", "これまでのあらすじ")}
    <p class="body">まず、天気が変わりました。そして天気は、居座りました。
    気象学者は「異常」と呼び、政府は「一時的」と呼び、雨はここを「我が家」と
    呼びました。いつからか雨は酸を帯び ― 雨に打たれた人々は、人では
    なくなりました。</p>
    <p class="body">誰がまだ中にいるのか確かめる前に、街は封鎖されました。
    というわけで、あなたはここにいます。生存者ひとり、乾いた服ひと揃い、
    そして救助との間に横たわる、封鎖された隔離ゾーン。電波塔は沈黙し、
    パラボラアンテナはバラバラ。死者たちは、気長です。</p>
    <p class="body">ルールその1：<b>濡れるな</b>。ルールその2：<b>食べろ</b>。
    ルールその3：存在しません。「ルールその3がある」と言う人は、あなたの傘を
    狙っています。</p>
    ${photo("shots/shot_flooded_cars.jpg", "図1 ― 長期駐車場。滞在はさらに長期に。", "tilt-l")}
    ${RUN}` });

  /* p4 — ゲージ --------------------------------------------------------------- */
  P.push({ no: 4, html: `
    ${head("2", "サバイバーの基本")}
    <p class="body">泥に還るまでの距離は、6つの数字で決まります。死者があなたを
    見張るように、常に見張りましょう。</p>
    <div class="gauges">
      <div class="gauge"><span class="g">体力</span><span class="d">あらゆるものがあなたを傷つけます。牙、空腹、渇き、そして雨そのもの。医療アイテムで回復するか、安全なベッドで眠って癒しましょう。</span></div>
      <div class="gauge"><span class="g">スタミナ</span><span class="d">ダッシュ、殴打、よじ登り ― 全部で減ります。ひと口の食料か飲み物で、脚のバネが戻ります。</span></div>
      <div class="gauge"><span class="g">空腹</span><span class="d">ゆっくり、しかし容赦なく減っていきます。ゼロになると、胃袋が<i>あなた</i>を食べ始めます。そうさせないこと。</span></div>
      <div class="gauge"><span class="g">渇き</span><span class="d">空腹より速く減ります。まわりは水だらけなのに、飲める水は一滴もない ― ゾーンのささやかなジョークです。</span></div>
      <div class="gauge"><span class="g">pHメーター</span><span class="d">雨に対する肌の耐久値。屋根の下で回復し、ゼロになると雨が焼き始めます。</span></div>
      <div class="gauge"><span class="g">バッテリー</span><span class="d">ライト<i>と</i>マップの電源。両方同時に使うと倍の速さで減ります。暗闇はタダ ― ただし高くつきます。</span></div>
    </div>
    ${photo("shots/shot_map_rain.jpg", "図2 ― マップを開いて、ライトも点けて。支払いはバッテリー持ち。", "tilt-r")}
    ${RUN}` });

  /* p5 — アクション ------------------------------------------------------------ */
  P.push({ no: 5, html: `
    ${head("3", "サバイバーアクション", "割り当てはオプションで変更可能")}
    <table class="ctl">
      <tr><td>移動／視点</td><td>行きたい場所へ。来るものを見逃さずに</td></tr>
      <tr><td>ダッシュ</td><td>歩くより速く、歩くよりお腹が空く</td></tr>
      <tr><td>ジャンプ</td><td>フェンス、隙間、劇的な退場に</td></tr>
      <tr><td>エイム</td><td>手の中の武器を構える</td></tr>
      <tr><td>射撃／使用</td><td>撃つ、振る、食べる、飲む、巻く ― 装備しているものしだい</td></tr>
      <tr><td>ズーム</td><td>スコープ付き武器のみ ― 面倒事はあちらが気づく前に</td></tr>
      <tr><td>リロード</td><td>弾切れの銃は、とても短い棍棒</td></tr>
      <tr><td>インタラクト</td><td>ドア、ベッド、乗り物、助けを待つ生存者</td></tr>
      <tr><td>インベントリ</td><td>長押しでパックの中をごそごそ</td></tr>
      <tr><td>ライト</td><td>灯り。対価はバッテリー</td></tr>
      <tr><td>捨てる</td><td>アイテムを置いていく ― 身軽な今、後悔は後で</td></tr>
      <tr><td>スコアボード</td><td>仲間の生存者たちの様子を見る</td></tr>
    </table>
    ${photo("shots/shot_survivor_action.jpg", "図3 ― 「射撃／使用」の実演。レイヴン・ハンドガン。", "tilt-l")}
    ${RUN}` });

  /* p6 — 雨 --------------------------------------------------------------------- */
  P.push({ no: 6, cls: "stained", html: `
    ${head("4", "雨")}
    <p class="body">雨はゾーンの大家であり、家賃はあなたの皮膚です。屋根のない
    場所では<b>pHメーター</b>が下がっていきます。ゼロになると、酸が体力を
    削り始め ― 頭の上に屋根が来るまで、止まりません。</p>
    <div class="warnbox" style="margin:.5em 0">
      <p class="body typewriter" style="text-align:center;margin:0">
      「pHレベル ゼロ ― 屋根のある場所を見つけて、酸性雨のダメージを防いでください。」<br>
      <span style="font-size:.85em;color:var(--ink-soft)">― これを最後まで読めなかった生存者もいます</span></p>
    </div>
    <p class="body"><span class="lead">屋根</span>とは、頭上にある固いものすべて。
    出入口、バス停、ガード下、他人のキャラバンの屋根。屋根の下では滴が止まり、
    メーターは息を吹き返します。ベッドで眠れば、最悪の時間も快適に
    やり過ごせます。</p>
    ${photo("shots/shot_umbrella_rain.jpg", "図4 ― 西の橋で目撃。お手本のような生存者。", "tilt-r")}
    ${RUN}` });

  /* p7 — 雨と装備 ----------------------------------------------------------------- */
  P.push({ no: 7, cls: "stained", html: `
    ${head("5", "雨と装備")}
    <p class="body">雨が狙うのはあなただけではありません ― あなたの衣装棚も
    です。外にいる間、マスクも、服も、ブーツも、静かに朽ちていきます。
    <b>防水性</b>の高い装備は濡れるのが遅く、耐久値ゼロの装備は
    <i>ゴミ</i>と呼ばれます。</p>
    <h2 class="rule">傘の尊い犠牲</h2>
    <p class="body">傘を差せば、雨によるダメージは<b>すべて</b>傘が引き受けます。
    差している間、服はいっさい濡れません。もちろんその間、傘はあなたの
    身代わりに死んでいきます。ついに壊れたら、短い黙祷を捧げて、次の一本を
    探しましょう。このゾーンは英国的なので、傘はどこにでもあります。</p>
    <h2 class="rule">参考文献</h2>
    <p class="body">役に立つジャーナルがあります。『レインウォーカーのジャーナル』は
    身につけた装備すべてを濡れにくくし、『pH入門のジャーナル』は雨の合間のメーター回復を
    早めます（20ページ参照）。</p>
    <div class="fieldnote">傘は囮であり、盾であり、屋根であり、杖である。
    このゾーンの天気を設計した奴は、傘も大量に置いていった。上の誰かが
    罪悪感を抱いていると、私は信じることにしている。 <b>― M.</b></div>
    ${RUN}` });

  /* p8-13 — 武器庫 ------------------------------------------------------------------ */
  P.push({ no: 8, html: `
    ${head("6", "武器庫", "ハンドガン")}
    <p class="body">6挺のハンドガン。すべて鳥の名前ですが、どれも飛びません。
    軽く、素早く構えられ、室内の非情な距離で真価を発揮します。</p>
    ${RSZ_ORDER.handgun.map(spec).join("")}
    ${RUN}` });

  P.push({ no: 9, html: `
    ${head("6", "武器庫", "ライフル")}
    <p class="body">問題は遠くで処理したい人へ。スコープ付き、遅くて慎重 ―
    雨と同じように。</p>
    ${RSZ_ORDER.rifle.map(spec).join("")}
    ${RUN}` });

  P.push({ no: 10, html: `
    ${head("6", "武器庫", "ショットガン")}
    <p class="body">近距離の不信任決議。拡散とは、「外した」と言わずに済む
    ということです。</p>
    ${RSZ_ORDER.shotgun.map(spec).join("")}
    ${RUN}` });

  P.push({ no: 11, html: `
    ${head("6", "武器庫", "クロスボウ")}
    <p class="body">静かで、優雅で、湿気た火薬とも無縁。一射につき一矢 ―
    一本一本を、熟慮の一票に。</p>
    ${RSZ_ORDER.crossbow.map(spec).join("")}
    ${RUN}` });

  P.push({ no: 12, html: `
    ${head("6", "武器庫", "傘")}
    <p class="body">そう、武器です。力強い一振りは、生者も死者も等しく
    遠ざけます ― 攻撃力が2種類あることにご注目。そして差している間は、
    服を雨から完全に守ります（7ページ）。</p>
    ${RSZ_ORDER.umbrella.map(spec).join("")}
    ${RUN}` });

  P.push({ no: 13, html: `
    ${head("6", "武器庫", "弾薬")}
    <p class="body">大小の箱で見つかります。口径は手の中の鳥に合わせること ―
    ライフル弾はスパロー・ハンドガンには入りません。どんなに押し込んでも。</p>
    <div class="grid cols2">${RSZ_ORDER.ammo.map(gitem).join("")}</div>
    ${photo("shots/shot_armed_survivor.jpg", "図5 ― 手の中のブルフィンチは、スーパーの2羽に勝る。", "tilt-l")}
    <div class="fieldnote">大きい箱は回り道の価値あり。弾は軽い。
    撃てなかった後悔はもっと重い。 <b>― M.</b></div>
    ${RUN}` });

  /* p14-17 — 装備 -------------------------------------------------------------------- */
  P.push({ no: 14, html: `
    ${head("7", "装備", "マスク")}
    <p class="body">名前は昆虫、守るのはもっと悪いものから。良いマスクは雨から
    顔を、牙から喉を守ります ― 防水と防御、両方の表記をチェック。</p>
    <div class="grid cols2">${RSZ_ORDER.mask.map(gitem).join("")}</div>
    ${RUN}` });

  P.push({ no: 15, html: `
    ${head("7", "装備", "服")}
    <p class="body">12着の服。すべてカモの名前です ― ゾーンでいまだに天気を
    楽しんでいる、唯一の住人たち。まず雨に備え、次に牙に備えて
    着ましょう。</p>
    <div class="grid cols2">${RSZ_ORDER.jacket.map(gitem).join("")}</div>
    ${RUN}` });

  P.push({ no: 16, html: `
    ${head("7", "装備", "ブーツ")}
    <p class="body">名前は英国の名峰から。あなたの足が登るのは、まさにそれだから
    です。良いブーツは水たまりをものともせず、歩幅を伸ばします ―
    スタミナの表記に注目。</p>
    <div class="grid cols2">${RSZ_ORDER.boots.map(gitem).join("")}</div>
    ${RUN}` });

  P.push({ no: 17, html: `
    ${head("7", "装備", "バックパック")}
    <p class="body">名前は英国の野生動物から。ただし、あなたがこれから運ぶ量を
    運べる動物は一匹もいません。スーパーまで泳いで4マイルの世界では、
    容量こそがすべてです。</p>
    <div class="grid cols2">${RSZ_ORDER.backpack.map(gitem).join("")}</div>
    ${photo("shots/shot_backpack_walk.jpg", "図6 ― 全財産を、標準支給のヘッジホッグ・バックパックに。", "tilt-r")}
    ${RUN}` });

  /* p18-19 — 食料 ---------------------------------------------------------------------- */
  P.push({ no: 18, html: `
    ${head("8", "食料", "保存食")}
    <p class="body">ゾーンの食文化は、缶詰・包装済み・フリーズドライの三択です。
    それでも「食べない」よりは、はるかに上等。食事は脚のバネも
    取り戻します。</p>
    <div class="grid cols2">${RSZ_ORDER.food.map(gitem).join("")}</div>
    ${photo("shots/shot_looting.jpg", "図7 ― 昼食。たぶん3番通路のあたり。", "tilt-l")}
    ${RUN}` });

  P.push({ no: 19, html: `
    ${head("8", "食料", "飲み物と応急手当")}
    <h2 class="rule">飲み物</h2>
    <div class="grid cols2">${RSZ_ORDER.drink.map(gitem).join("")}</div>
    <h2 class="rule">応急手当</h2>
    <div class="grid cols2">${RSZ_ORDER.medical.map(gitem).join("")}</div>
    <div class="fieldnote">小さい包帯はかすり傷に。大きいのは、あとで語り草に
    なる傷に。抗生物質は、あなたがどれだけ勇敢だったかに興味がない。
    <b>― M.</b></div>
    ${RUN}` });

  /* p20-21 — ジャーナル ------------------------------------------------------------------ */
  const J = RSZ_ORDER.journal;
  P.push({ no: 20, html: `
    ${head("9", "サバイバーのジャーナル")}
    <p class="body">他の生存者たちが、学んだことを書き残しました。ジャーナルを
    持ち歩けば、その知恵があなたのために働きます ― ただし、どれも壊れ物。
    <b>知恵は、使われるたびにすり減ります</b>。もつ長さは知恵の中身しだい ―
    一歩ごとに開かれる本と、嵐ごとに開かれる本とでは、傷み方が違います。
    ついに破れたとき、知恵も一緒に失われます。二冊目を見かけたら、
    確保しておきましょう。</p>
    ${J.slice(0, 7).map(jitem).join("")}
    ${RUN}` });

  P.push({ no: 21, html: `
    ${head("9", "サバイバーのジャーナル", "つづき")}
    ${J.slice(7).map(jitem).join("")}
    <div style="width:86%; margin:0 auto">${photo("shots/shot_horse_umbrella.jpg", "図8 ― 『頑固な獣のジャーナル』の卒業生。傘つきでお出かけ中。", "tilt-r")}</div>
    ${RUN}` });

  /* p22-23 — ミッション（説明文はゲーム内公式テキスト） ------------------------------------- */
  P.push({ no: 22, html: `
    ${head("10", "ミッション", "施錠された扉")}
    <p class="body">ゾーンの扉のいくつかは、正しいプラスチックのカードにしか
    開きません。前の持ち主には、もう不要です。たぶん。</p>
    <div class="grid cols3" style="margin-bottom:3%">${["PoliceKeycardBP", "MilitaryIDBP", "BunkerKeycardBP"].map(gitem).join("")}</div>
    <p class="body">「秘密のバンカーへの忘れられたキーカードが町のどこかに落ちて
    います。それを回収し、封印されたドアを開けて地下の秘密を暴きましょう。」
    警察署の武器庫も、軍事基地も、同じ流儀で待っています。中に何があるかは、
    あなたと扉の問題です。</p>
    <div class="mcards">
      <div class="mcard"><img src="assets/ui/mission_police.png" alt="警察署ミッションカード"></div>
      <div class="mcard"><img src="assets/ui/mission_military.png" alt="軍事基地ミッションカード"></div>
      <div class="mcard"><img src="assets/ui/mission_bunker.png" alt="バンカーミッションカード"></div>
      <div class="mcard"><img src="assets/ui/mission_radiotower.png" alt="電波塔ミッションカード"></div>
    </div>
    ${RUN}` });

  P.push({ no: 23, html: `
    ${head("10", "ミッション", "信号と生存者たち")}
    <p class="body">「無線のパーツを3つ見つけて電波塔に持ち帰り、他の生存者を
    助けて報酬を得ましょう。」パラボラアンテナも同様です ― 3つの重要な
    パーツが町に散らばっています。すべて見つけて、高い屋上へ。</p>
    <div class="grid cols2" style="margin-bottom:3%">${["RadioTowerPartBP", "SatelliteDishPartBP"].map(gitem).join("")}</div>
    <p class="body">あなたは最後のひとりではありません。飢えで衰弱している者、
    死にかけている者、そして理由を明かさずにハンドガンを求める者。助ければ、
    あなたの物資が減ります。助けなければ、もっと補充しにくいものが
    減ります。</p>
    <div class="mcards">
      <div class="mcard"><img src="assets/ui/mission_satellitedish.png" alt="パラボラアンテナミッションカード"></div>
      <div class="mcard"><img src="assets/ui/mission_survivor_food.png" alt="生存者（食料）ミッションカード"></div>
      <div class="mcard"><img src="assets/ui/mission_survivor_medical.png" alt="生存者（治療）ミッションカード"></div>
      <div class="mcard"><img src="assets/ui/mission_survivor_handgun.png" alt="生存者（ハンドガン）ミッションカード"></div>
    </div>
    ${RUN}` });

  /* p24-25 — ゾーン（地図見開き） ----------------------------------------------------------- */
  const GAZ = [
    ["廃鉱", "暗い、深い、看板に偽りなし"],
    ["サウスサイド空港", "全便欠航（未来永劫）"],
    ["秘密のバンカー", "ゾーンで一番バレている秘密"],
    ["キャラバンパーク", "別荘地、シーズン絶賛延長中"],
    ["シティ駐車場", "空きあり"],
    ["シティ大聖堂", "屋根はいまだに雨を通さない"],
    ["デラックス・シネマ", "上映中の一本、永遠に"],
    ["孤立した農家", "「静かな環境」はもう売り文句にならない"],
    ["住宅アパート", "ご近所は史上もっとも静か"],
    ["ヘイルズ・アパートメント", "高級住宅、多少の傷みあり"],
    ["廃ホテル", "空室あり"],
    ["南東工業地帯", "重機は重厚、警備は手薄"],
    ["アイランドハウス", "不動産屋いわく「趣がある」"],
    ["レイクサイド・コテージ", "今や全方位ウォーターフロント"],
    ["軍事基地", "要ID（22ページ）"],
  ];
  const GAZ2 = [
    ["古い製粉所", "あの日以来、挽くのをやめた"],
    ["南ガソリンスタンド", "ポンプは空。棚は、どうかな"],
    ["東ガソリンスタンド", "上に同じ。ただし東"],
    ["北ガソリンスタンド", "景色の良いほう"],
    ["警察署", "要キーカード（22ページ）"],
    ["冷却塔", "中は見事に乾いている"],
    ["鉄道車両基地", "終着点"],
    ["シティ駅", "代行バスも運休中"],
    ["電波塔", "沈黙中、修理可能（23ページ）"],
    ["廃高校", "学期は早めに終わった"],
    ["ショッピングモール", "在庫一掃。そして一掃された"],
    ["破壊された超高層ビル", "短期滞在向け"],
    ["草生したスタジアム", "ピッチはかつてなく青々"],
    ["荒らされたスーパーマーケット", "3番通路をチェック（図7）"],
    ["地下鉄駅", "足元と、その他諸々にご注意"],
  ];
  P.push({ no: 24, html: `
    ${head("11", "ゾーン", "西")}
    <div class="mapwrap"><img src="assets/art/map.jpg" alt="隔離ゾーン地図（西側）"></div>
    ${gaz(GAZ)}
    ${RUN}` });
  P.push({ no: 25, html: `
    ${head("11", "ゾーン", "東")}
    <div class="mapwrap"><img src="assets/art/map.jpg" alt="隔離ゾーン地図（東側）"></div>
    ${gaz(GAZ2)}
    ${RUN}` });

  /* p26 — アンデッド --------------------------------------------------------------------- */
  P.push({ no: 26, cls: "stained", html: `
    ${head("12", "アンデッド", "現地の記録")}
    <p class="body typewriter">生存者の証言より編纂。検閲局が確認できなかった
    記述は、読者の安全のため黒塗りにしてあります。</p>
    <p class="body">かつては人でした。雨が染み込む前までは。彼らは一番近くに
    いる者を狩ります ― このゾーンでは、それはたいてい、あなたです。疲れず、
    雨宿りせず、その傘がいくらしたかにも興味はありません。</p>
    <p class="body">力強い一撃は、飛びかかる寸前の一体をよろめかせます。
    そして力強い何かがあれば、仕留めきれます。彼らも他のみんなと同じように
    倒れます ― ただ、ためらいが少ないだけ。生存者の報告によると、乾いた個体は
    <span class="redacted">黒塗り黒塗り</span>、雨に濡れた個体は
    <span class="redacted">全部黒塗り</span>。<span class="redacted">これは
    絶対に印刷できない。</span></p>
    <div class="cols">
      <div>${photo("shots/shot_zombie_attack.jpg", "図9 ― 近すぎる。早くページをめくって。", "tilt-l")}</div>
      <div>${photo("shots/shot_zombie_pair.jpg", "図10 ― 現地スケッチ：ドライゾンビ。", "tilt-r")}</div>
    </div>
    <div class="fieldnote">何を持っていようと、もっと強く握れ。 <b>― M.</b></div>
    ${RUN}` });

  /* p27 — マルチプレイヤー ------------------------------------------------------------------ */
  P.push({ no: 27, html: `
    ${head("13", "共に生き延びる")}
    <p class="body">ゾーンは、一匹狼から順に連れていきます。仲間と組めば、
    マップも、戦利品も、乗り物も、責任も分け合えます。ひとりが傘を持ち、
    ひとりがショットガンを持つ ― 文明の再建です。</p>
    <p class="body"><span class="lead">手を振ろう。</span>見知らぬ生存者に出会ったら、
    「メッセージ」メニューを開いて<b>手を振り</b>ましょう。相手も振り返して
    くれたら、フレンド成立。以後、ゾーンのどこにいても互いのネームタグが
    見えるようになり、武器は<b>フレンドを傷つけなくなります</b> ― どんなに
    照準が下手でも。友情が、ゲームの仕組みとして働くのです。私たちの知る限り、
    友情が防弾仕様なのはこのゾーンだけです。</p>
    <p class="body"><span class="lead">照準について。</span>手を振り合うまでは、
    武器は着弾前に敵味方を確認しません。見知らぬ相手にはダメージが入ります。
    逸れたイーグル・ハンドガンの一発で終わった間柄もあります。撃つ前に確認を
    ― いや、先に手を振りましょう。</p>
    <p class="body"><span class="lead">分担について。</span>困っている生存者への
    物資（23ページ）は、あなたのパックから出ていきます。出発前に買い出し
    リストを分担しましょう。まっとうな決死隊なら、誰でもそうするように。</p>
    <p class="body"><span class="lead">沈まないセッション。</span>ホストが抜ける
    ことになっても ― 救助でも、癇癪でも、就寝時間でも ― RAIN STATION Zの
    専用設計・独自実装の<b>ホストマイグレーション</b>が、嵐の真っ只中でも
    ゾーンごと別のプレイヤーへ引き継ぎます。世界も、戦利品も、「誰が
    ショットガンの弾を無駄にしたか」の口論も、何事もなかったように続行。</p>
    <p class="body"><span class="lead">声に出して言おう。</span>フリーテキスト
    チャット搭載、フルオンスクリーンキーボード付き（29ページ）。連携し、
    交渉し、謝りましょう。</p>
    <div style="width:88%; margin:0 auto">${photo("shots/shot_two_survivors.jpg", "図11 ― お揃いの装備。威嚇か友情か。たいてい両方。", "tilt-l")}</div>
    ${RUN}` });

  /* p28 — フォトモード ------------------------------------------------------------------------ */
  P.push({ no: 28, html: `
    ${head("14", "フォトモード", "プラクティスモード限定")}
    <p class="body">ゾーンの景色は、おぞましさと美しさがほぼ半々。だから
    プラクティス探索キットには、本格的なカメラ一式が付いてきます。自由に
    動くレンズと、世界の終わりを演出する11本のスライダーです。</p>
    <div class="warnbox" style="margin:.4em 0">
      <p class="body typewriter" style="text-align:center;margin:0">
      シングルプレイヤーの<b>プラクティスモード</b>専用。<br>
      <span style="font-size:.85em;color:var(--ink-soft)">マルチプレイヤーのフリーカメラは観戦用です ― スライダーなし、
      ポーズなし。あなた抜きでやっていく仲間を、ただ見守るだけ。</span></p>
    </div>
    <div class="cols" style="font-family:'DotGothic16',monospace; font-size:11.5px; line-height:1.6">
      <div>視野角 ― 広角から望遠まで<br>
      フォーカス距離 ― ピントに値するものを選ぶ<br>
      被写界深度 ― 直せないものは、全部ぼかす<br>
      彩度 ― 絵葉書から絶望まで<br>
      コントラスト ― 陰影を深くも、平坦にも<br>
      ホワイトバランス ― 終末を少し暖色に</div>
      <div>レンズの雨粒 ― ガラスの水滴、オンデマンド<br>
      ブルーム ― ライトの灯を歌わせる<br>
      レンズフレア ― 太陽がまだ来ると信じたい<br>
      ビネット ― 迫りくる闇を、芸術的に<br>
      フィルムグレイン ― 一瞬で35mm<br>&nbsp;</div>
    </div>
    <div class="cols">
      <div>${photo("shots/shot_photomode_bw.jpg", "図12 ― ビネット全開、彩度ゼロ。", "tilt-l")}</div>
      <div>${photo("shots/shot_photomode_blue.jpg", "図13 ― 同じ通り、ブルーな気分。", "tilt-r")}</div>
    </div>
    ${RUN}` });

  /* p29 — フィールド機能 ------------------------------------------------------------------------ */
  const FEATS = [
    ["一続きのオープンワールド隔離ゾーン", "30の名所。外周は封鎖、内側はどこへでも"],
    ["オンラインマルチプレイヤー", "世界も、戦利品も、責任も共有"],
    ["専用設計のホストマイグレーション", "独自実装。ホストが抜けても、セッションは新経営のもと続行"],
    ["フリーテキストチャット", "フルオンスクリーンキーボードで、連携・取引・謝罪"],
    ["手を振って、フレンドに", "振り返してくれたら成立 ― ネームタグはゾーン中で見え、武器は互いを傷つけない"],
    ["プラクティスモード", "ゾーンをひとり占め。カメラ一式つき（28ページ）"],
    ["フォトモード", "ギャラリー作品まで、あとスライダー11本"],
    ["騎乗できる獣たち", "ゾーンの馬は頑固だが、交渉の余地あり"],
    ["意志を持つ天気", "体力と、衣服と、傘を狙う酸性雨"],
    ["昼と夜", "ライトを持て。電池は多めに"],
    ["100種類超のアイテム", "集めるのは鳥、カモ、昆虫、獣、名峰"],
    ["助けを待つ生存者たち", "助けるか、渡すか、食わせるか ― あるいは、見捨てて生きるか"],
  ];
  P.push({ no: 29, html: `
    ${head("15", "フィールド機能", "パッケージ裏面より")}
    <div style="margin:.4em 0 .8em">${FEATS.map(([f, d]) =>
      `<div class="gauge"><span class="g" style="width:34%">&#9745; ${f}</span><span class="d">${d}</span></div>`).join("")}
    </div>
    ${photo("ui/keyboard.png", "図14 ― ゾーン公式フルQWERTY。左下の「手を振る」ボタンに注目。言葉遣いに注意 ― 死者が聞いています。", "tilt-l")}
    ${RUN}` });

  /* p30 — ノート ------------------------------------------------------------------------------- */
  P.push({ no: 30, html: `
    ${head("&#9998;", "フィールドノート", "自由記入欄")}
    <div class="ruled">
      <span style="position:absolute; top:0; left:2%">無事故日数：&nbsp;&nbsp;0</span>
      <div class="coffeering"></div>
    </div>
    ${RUN}` });

  /* p31 — クレジット ----------------------------------------------------------------------------- */
  P.push({ no: 31, cls: "stained", html: `
    ${head("&#10045;", "クレジット")}
    <div style="text-align:center; margin-top:6%">
      <p class="typewriter" style="letter-spacing:.25em; font-size:13px">制作</p>
      <p style="font-family:'Oswald',sans-serif; font-weight:700; text-transform:uppercase; font-size:28px; letter-spacing:.08em">Wobbly Tooth Limited</p>
      <p class="typewriter" style="margin-top:4%; font-size:12px; color:var(--ink-soft)">
        wobbly-tooth.com</p>
      <div style="margin:8% auto; width:50%; border-top:1px solid var(--ink-soft)"></div>
      <p class="body" style="text-align:center">本書は、正真正銘のゾーン実地調査
      データ、目撃証言、そして生存者M.の書き込みをもとに編纂されました。
      M.の消息は不明。傘は差したままと思われます。</p>
      <p class="body" style="text-align:center">武器の評価は、すべて同クラス内の
      相対値です。本書の制作にあたり、数値はいっさい印刷されて
      いません。</p>
      <p class="typewriter" style="margin-top:6%; font-size:11px; color:var(--ink-soft)">
        &copy; Wobbly Tooth Limited. All rights reserved.<br>
        ゾーン内にて印刷。二度乾燥済み。</p>
    </div>
    ${RUN}` });

  /* 裏表紙 ---------------------------------------------------------------------------------------- */
  P.push({ no: null, cls: "cover", html: `
    <div class="art" style="margin-top:10%">${photo("shots/shot_horse_night.jpg", "")}</div>
    <p style="font-family:'Noto Sans JP',sans-serif; font-weight:900; letter-spacing:.25em; font-size:21px; margin:6% 0 2%">濡れるな、死ぬな。</p>
    <p class="typewriter" style="font-size:11px; color:#c8bea4">wobbly-tooth.com/RainStationZ</p>
    <div class="badges" style="margin-bottom:2%">
      <span class="badge">Steam</span>
      <span class="badge">PlayStation 5</span>
      <span class="badge">Nintendo Switch</span>
    </div>
    <div class="barcode"></div>
    <div class="barcode-num">5 014416 000000</div>` });

  return P;
};
